### ISSUE TITLE
Nouvelle fonctionnalité : exporter la synthèse d'un audit

### ISSUE THREAD

**Issue by thombeck** [Asqatasun/Asqatasun#108]
Actuellement, on peut faire des exports de l'audit d'une page uniquement.
Ce serait intéressant de pouvoir faire un export de la synthèse complète des audits.

Merci !

**Comment by dzc34** [comment]
duplicate  [Have a global export (scope page + scope site + global data) #79 ](https://github.com/Asqatasun/Asqatasun/issues/79)

**Comment by dzc34** [comment]
added to #175
