### ISSUE TITLE
DOC - helps the referential creation

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#112]
## Observed behaviour

no documentation to help the referential creation : 
- [rules/referential-creator](https://github.com/Asqatasun/Asqatasun/tree/master/rules/referential-creator)
- [rules/referential-creator-maven-plugin](https://github.com/Asqatasun/Asqatasun/tree/master/rules/referential-creator-maven-plugin)

**Comment by dzc34** [comment]
it's here, but a refactoring is needed Modifier
https://github.com/Asqatasun/Asqatasun/tree/develop/documentation/en/30_Contributor_doc/Referential-Creator

**Comment by mfaure** [comment]
@dzc34 what do you mean "a refactoring is needed" ?

**Comment by dzc34** [comment]
- maybe change the directory name and filenames ?
- adding into documentation/en/SUMMARY.md
- README.md is empty
- the links are broken for ElementSelector, ElementChecker and TextElementBuilder (see @@@TODO fix URL)
- ...

**Comment by mfaure** [comment]
DONE for:

* maybe change the directory name and filenames ?
* adding into documentation/en/SUMMARY.md
* README.md is empty

Work in Progress for the links to ElementSelector, ElementChecker and TextElementBuilder

**Comment by dzc34** [comment]
in [10--How-to-create-your-own-referential.html](http://doc.asqatasun.org/en/30_Contributor_doc/Referential-Creator/10--How-to-create-your-own-referential.html) we can read :
> Install manually the apache commons-csv library. 
>       cd Asqatasun/rules/referential-creator-maven-plugin/src/main/resources/lib/
>       ./install_lib.sh 

- `/rules/referential-creator-maven-plugin/src/main/resources/lib/` does not exist
- it does not need to install manually the apache commons-csv library to create a new referential

**Comment by mfaure** [comment]
DONE

**Comment by dzc34** [comment]
no @mfaure it's WIP !!

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
