### ISSUE TITLE
RGAA 3 2016 compliant

### ISSUE THREAD

**Issue by okeul** [Asqatasun/Asqatasun#118]
Il faudrait mettre la checklist (et donc les tests et les critères) à jour avec la dernière version du RGAA : [RGAA 3 2016](http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html)

La note de révision : http://references.modernisation.gouv.fr/rgaa-accessibilite/changelog.html

**Comment by dzc34** [comment]
replaced  #163 "RGAA 3 2017 compliant"
