### ISSUE TITLE
Have functionnal test to execute once an installation is made

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#12]
In order to verify an installation is OK, we have to verify each functionnality.
Some tests (Selenium) may exist somewhere in the projects: go find them !
Then Enhance them.

Those tests should verify

* user creation
* contract creation
* audit
    * RGAA3 page
    * RGAA3 site
    * RGAA3 file
    * RGAA3 scenario
    * RGAA3 manual
    * SEO site
* mail is sent

**Comment by dzc34** [comment]
no .json file to test the web application
only files .json here:
- `/engine/scenarioloader/src/test/resources`
- `/rules/rules-XXX/src/test/resources/testcases/XXX/XXXRuleYYY`

command line used
`find ./ -name "*.json"  `

**Comment by mfaure** [comment]
Well, fairly done ! \o/
http://doc.asqatasun.org/en/30_Contributor_doc/Testing/Functional_tests.html
https://pbs.twimg.com/tweet_video/CfS48RGWEAAOHhi.mp4
