### ISSUE TITLE
Webapp - avoid user launching 2 site-audits consecutively

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#120]
## Observed behaviour

For a given project, user launches a site audit. He/she can go back to his dashboard (for the same project) and launching another site-audit on the same site.

He/she may not understand the audit currently running.  

Also, he/she may fill in rapidly the pool of the server by repeating this action many times, leading to block all other users of the server.
## Expected behaviour

Once a site-audit is launched by a user, disable the site-audit icon until the previous site-audit is done (with success or error, we don't mind).
## Steps to reproduce the behaviour

(explained above)
## Your configuration
- Asqatasun version (in the footer of any webpage) --> 4.0.3
- Using Docker image ? --> No

**Comment by dzc34** [comment]
added to #175 and closed
