### ISSUE TITLE
Need means to install on RHEL (Red Hat Enterprise Linux)

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#121]
Desperately need process/steps to install on RHEL... couple of libraries im unable to find equivalent on rhel... i will still try out but need help

**Comment by mfaure** [comment]
Hi @softwareklinic, which package do you need / miss ?

**Comment by softwareklinic** [comment]
will try.to setup again today

Sent from my iPhone

On Sep 17, 2016, at 3:43 PM, Matthieu FAURE <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @softwareklinic<https://github.com/softwareklinic>, which package do you need / miss ?

**Comment by dzc34** [comment]
@softwareklinic 
Do you find libraries equivalent on rhel ?

**Comment by softwareklinic** [comment]
Will try over.the weekend.

Sent from my iPhone

On Sep 21, 2016, at 6:30 PM, Fabrice Gangler <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic>
Do you find libraries equivalent on rhel ?

**Comment by mfaure** [comment]
For your information, I'm working on having a clear definition of pre-requisites and dependencies on RHEL / CentOS. Nevertheless, I would be happy to have you errors.

**Comment by dzc34** [comment]
This type of discussion can continue
in the forum http://forum.asqatasun.org/

**Comment by dzc34** [comment]
This type of discussion can continue
in the forum http://forum.asqatasun.org/
