### ISSUE TITLE
Firefox latest edition 48.0.2

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#122]
I'm trying a json script for a scenario -- and the script constantly keeps failing with locator error.. unable to find ---- i have verified that the script works just fine from SE builder to my selenium server running firefox 48.0.2 --- can i not replace the firefox edition for asqatasun from 31.xxxx to 48.0... or can u help me look @ whats causing it... on the FF 31.xxxx

**Comment by jkowalczyk** [comment]
Hi, 

Do you use a selenium grid to make your test? 
Can you send us the log trace? 
What do you mean by **can i not replace** ?

Regards 
Koj

**Comment by mfaure** [comment]
@softwareklinic you have to replace your Firefox, quite easy:

I assume your host is 64bit (x86_64)

```sh
sudo rm -rf /opt/firefox
cd /opt
sudo wget --passive http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/31.4.0esr/linux-x86_64/en-US/firefox-31.4.0esr.tar.bz2
sudo tar xvfj firefox-31.4.0esr.tar.bz2
sudo mv firefox firefox-31.4.0esr
sudo ln -s firefox-31.4.0esr firefox
```

Explanation line by line:

* line 1: remove previous Firefox
* line 2: go to /opt
* line 3: download Firefox 31.4
* line 4: uncompress the Firefox archive just downloaded
* line 5: rename the folder created by the archive from /opt/firefox to /opt/firefox-31.4.0esr
* line 6: add a symbolic link named /opt/firefox to /opt/firefox-31.4.0esr

Tell us how it goes

**Comment by softwareklinic** [comment]
Did.that.using.latest.Firefox 48.0.2

But.seeing.some.error while.running tests.related.to Firefox.profile

Will share logs

Sent from my iPhone

On Sep 19, 2016, at 3:00 AM, Matthieu FAURE <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> you have to replace your Firefox, quite easy:

I assume your host is 64bit (x86_64)

sudo rm -rf /opt/firefox
cd /opt
sudo wget --passive http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/31.4.0esr/linux-x86_64/en-US/firefox-31.4.0esr.tar.bz2
sudo tar xvfj firefox-31.4.0esr.tar.bz2
sudo mv firefox firefox-31.4.0esr
sudo ln -s firefox-31.4.0esr firefox

Explanation line by line:

 *   line 1: remove previous Firefox
 *   line 2: go to /opt
 *   line 3: download Firefox 31.4
 *   line 4: uncompress the Firefox archive just downloaded
 *   line 5: rename the folder created by the archive from /opt/firefox to /opt/firefox-31.4.0esr
 *   line 6: add a symbolic link named /opt/firefox to /opt/firefox-31.4.0esr

Tell us how it goes

**Comment by mfaure** [comment]
Thanks for your feedback. As volunteers, we love to help our users. Here are a few lines that may increase your involvement in a community of volunteers http://catb.org/~esr/faqs/smart-questions.html#writewell and the whole article is also interesting http://catb.org/~esr/faqs/smart-questions.html :)

**Comment by jkowalczyk** [comment]
You cannot install any firefox version. The application is built with a given version of webdriver which is compatible with a given version of firefox. 
That's why the installation doc specifies explicitely the firefox to install ; it is to garantee the compatibility.
Hope it helps.

Koj

**Comment by softwareklinic** [comment]
Can I customize.the code/replace.driver jar .to use.the latest firefox version ?

Sent from my iPhone

On Sep 19, 2016, at 7:08 AM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


You cannot install any firefox version. The application is built with a given version of webdriver which is compatible with a given version of firefox.
That's why the installation doc specifies explicitely the firefox to install ; it is to garantee the compatibility.
Hope it helps.

Koj

**Comment by jkowalczyk** [comment]
You can give it a try, but this may lead to strange behaviours that will be hard to debug and I'd not recommend it.
Before running firefox, a tuned profile is set-up to ensure that no update is enable, there is no default page and so on....
By upgrading firefox, you need to ensure that all these options are still supported, 
Furthermore, webdriver comes with dependencies and we are not sure that these new dependencies don't override some others.
So to sum-up, doing this may bring some instability to the whole system.

Why can't you install the requested firefox esr version ? 

Koj

**Comment by softwareklinic** [comment]
Actually - I have a JSON.script that.fails.at.certain point.while.locating am.element. It.works on.a.desktop selenium.and.Firefox.

Sent from my iPhone

On Sep 19, 2016, at 7:26 AM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


You can give it a try, but this may lead to strange behaviours that will be hard to debug and I'd not recommend it.
Before running firefox, a tuned profile is set-up to ensure that no update is enable, there is no default page and so on....
By upgrading firefox, you need to ensure that all these options are still supported,
Furthermore, webdriver comes with dependencies and we are not sure that these new dependencies don't override some others.
So to sum-up, doing this may bring some instability to the whole system.

Why can't you install the requested firefox esr version ?

Koj

**Comment by dzc34** [comment]
This type of discussion can continue
in the forum http://forum.asqatasun.org/
