### ISSUE TITLE
Incorrect string value: '\xF0\x9F\x99\x82" ...' for column 'Source'

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#123]
## Observed behaviour
- launch a page audit on https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-access
- Page with error: A problem occured while loading the content of the page.

*Edit 2017-06-13* [Testcases for this issue #123](http://nonreg.asqatasun.ovh/Issues/Issue-123/) have been created

## Expected behaviour

regular result of audit
## Steps to reproduce the behaviour
- Page audit (default RGAA 3.0 level Argent) on: 
  - http://nonreg.asqatasun.ovh/Issues/Issue-123/Dos_and_donts--Firefox-save-as.html
  - http://nonreg.asqatasun.ovh/Issues/Issue-123/Accueil_Ville_de_Cergy--Firefox-save-as.html
- error "A problem occured while loading the content of the page."
## Your configuration
- Asqatasun version (in the footer of any webpage) --> 4.0.3
- Using Docker image ? --> yes, but also seen on a regular install
## logs from /var/log/asqatasun.log

```
INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - Launching audit Page on https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
INFO  org.asqatasun.service.command.AbstractScenarioAuditCommandImpl  - Loading content for https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Incorrect string value: '\xF0\x9F\x99\x82" ...' for column 'Source' at row 1
WARN  com.sebuilder.interpreter.SeInterpreter  - org.hibernate.exception.GenericJDBCException: could not execute statement
WARN  com.sebuilder.interpreter.SeInterpreter  - org.hibernate.exception.GenericJDBCException: could not execute statement
WARN  org.asqatasun.scenarioloader.ScenarioLoaderImpl  - {"url":"https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/","negated":false} failed.
INFO  org.asqatasun.service.command.AbstractScenarioAuditCommandImpl  - https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/ has been loaded
INFO  org.asqatasun.service.command.AuditCommandImpl  - Adapting https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
WARN  org.asqatasun.service.AuditServiceImpl  - Audit has no corrected DOM
INFO  org.asqatasun.service.command.AuditCommandImpl  - https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/ has been adapted
WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whilePROCESSING was required
WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whileCONSOLIDATION was required
WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whileANALYSIS was required
INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - Audit page terminated on https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
```

**Comment by mfaure** [comment]
Suspected string:

```html
<p>Thank you Tom. <img draggable="false" class="emoji" alt="🙂" src="https://s.w.org/images/core/emoji/2/svg/1f642.svg"></p>
```

Carefully watch the `alt`

See also http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by mfaure** [comment]
A possible solution: http://stackoverflow.com/questions/13653712/java-sql-sqlexception-incorrect-string-value-xf0-x9f-x91-xbd-xf0-x9f#answer-13754976

**Comment by mfaure** [comment]
Updated description with links to testcases from http://nonreg.asqatasun.org/

**Comment by allrib** [comment]
We try to take it

**Comment by mfaure** [comment]
@allrib please open a pull request with your code (even if it is not tested, someone else can do that). Prefix the name of your PR with `WIP` so that people understand this is Work In Progress.

Thanks !

**Comment by dzc34** [comment]
@mfaure, "good first issue", really?

**Comment by dzc34** [comment]
```
 CREATE TABLE IF NOT EXISTS `AUDIT` (
   `Id_Audit` bigint(20) NOT NULL AUTO_INCREMENT,
-  `Comment` varchar(255) DEFAULT NULL,
+  `Comment` varchar(191) DEFAULT NULL,
```

some links for the `191` magical number:
- https://mathiasbynens.be/notes/mysql-utf8mb4#column-index-length
- https://stackoverflow.com/questions/48500355/mysql-character-set-utf8mb4-varchar-length
- https://stackoverflow.com/questions/20123824/how-can-i-alter-an-indexed-varchar255-from-utf8-to-utf8mb4-and-still-stay-unde
- https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5
- https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html

**Comment by dzc34** [comment]
@allrib your works is now on [`123_db-conversion-to-UTF8mb4` branch](https://github.com/Asqatasun/Asqatasun/commits/123_db-conversion-to-UTF8mb4)

**Comment by dzc34** [comment]
I have the same issue after #255
```bash
./docker/build_and_run-with-docker.sh  -l --source-dir $(pwd) --docker-dir docker/SNAPSHOT-local 
docker logs -f  asqa     
     ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Incorrect string value: '\xF0\x9F\x99\x82" ...' for column 'Source' at row 1

git log --online --decorate
     8ed869b (HEAD -> develop, origin/develop) Updated CHANGELOG
     218e771 Merge pull request #255 from Asqatasun/123_db-conversion-to-UTF8mb4
     c914688 Merge branch 'develop' into 123_db-conversion-to-UTF8mb4
     cf5ad80 Merge pull request #254 from Asqatasun/253_Adapt_installer_to_Java8
     f83ea2e Merge branch 'develop' into 253_Adapt_installer_to_Java8
```

**Comment by dzc34** [comment]
it's works with 6b05f713ea1eef45 and updating dockhub build

**Comment by mfaure** [comment]
Just for information, here is the canonical reference from **official Mysql 5.5 documentation**: 

[10.9.7 Converting Between 3-Byte and 4-Byte Unicode Character Sets](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html). 

And you will notice many other sites seem to have copy/pasted large parts of this doc, or maybe the opposite, who knows :)

**Comment by mfaure** [comment]
Another useful resource I've just created : [Memento Mysql - Character set and collation queries](https://gitlab.com/matt.faure/mfaure/blob/master/Memento/Memento:-mariadb-mysql.md#collation-and-character-set)

**Comment by mfaure** [comment]
How to configure JDBC datasource using utf8mb4: suffix `?useUnicode=yes&characterEncoding=UTF-8` to the `jdbc.url=...`

Sources:

* [StackOverflow answer to: JDBC and utf8mb4 encoding the emoji symbol 🔥](https://stackoverflow.com/questions/47060827/jdbc-and-utf8mb4-encoding-the-emoji-symbol#answer-47160833)
* [Connector/J JDBC Reference > Using Character Sets and Unicode](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html)

**Comment by rupeshd015** [comment]
Incorrect string value: '\xA0- (Bl...' for column 'deal_title' at row 1

**Comment by dzc34** [comment]
hi @rupeshd015, 

Can you provide more informations ?
* Steps to reproduce the behaviour (URL, ...)
* Your configuration:
     * Asqatasun version (in the footer of any webpage)
     * Using Docker image ?
