### ISSUE TITLE
some unit tests fail : subdomains of tgqa.org are disabled

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#127]
## Observed behaviour

The following subdomains are disabled
but  are used by some unit tests:
- http://site-sitemap.tgqa.org 
- http://site-robot.tgqa.org
- http://site.tgqa.org

The following files are concerned: 
- [ScenarioLoaderImplTest.java](https://github.com/Asqatasun/Asqatasun/blob/master/engine/scenarioloader/src/test/java/org/asqatasun/scenarioloader/ScenarioLoaderImplTest.java)
- [SeoRule01051Test.java](https://github.com/Asqatasun/Asqatasun/blob/master/rules/rules-seo1.0/src/test/java/org/asqatasun/rules/seo/SeoRule01051Test.java)
- [SeoRule01061Test.java](https://github.com/Asqatasun/Asqatasun/blob/master/rules/rules-seo1.0/src/test/java/org/asqatasun/rules/seo/SeoRule01061Test.java)
- [ sites-url.properties](https://github.com/Asqatasun/Asqatasun/blob/master/engine/crawler/src/test/resources/sites-url.properties)
- [ MyTest2.json](https://github.com/Asqatasun/Asqatasun/blob/master/engine/scenarioloader/src/test/resources/MyTest2.json)

**Comment by dzc34** [comment]
> ```
> engine/crawler/src/test/resources/sites/
> ├── index.html
> ├── page-1.html
> ├── page-2.html
> ├── page-access-forbidden-for-robots.html
> └── robots.txt
> ```

**Comment by dzc34** [comment]
The following subdomains are now reactivated. 
-     `http://site-sitemap.tgqa.org`
-    ` http://site-robot.tgqa.org`
-     `http://site.tgqa.org`

But we should have our own sub-domains...
-     `http://site-sitemap.qa.asqatasun.eu`
-    ` http://site-robot.qa.asqatasun.eu`
-     `http://site.qa.asqatasun.eu`

**Comment by mfaure** [comment]
Fixed. You can replace `tgqa.org` by `asqatasun.ovh` in the URLs.

By the way, the four associated projects have been created:

* https://github.com/Asqatasun/site.asqatasun.ovh
* https://github.com/Asqatasun/site-robot.asqatasun.ovh
* https://github.com/Asqatasun/site-robot-sitemap.asqatasun.ovh
* https://github.com/Asqatasun/site-sitemap.asqatasun.ovh

**Comment by dzc34** [comment]
* http://site.asqatasun.ovh
* http://site-robot.asqatasun.ovh
* http://site-robot-sitemap.asqatasun.ovh
* http://site-sitemap.asqatasun.ovh

**Comment by dzc34** [comment]
fixed 7ffc6437f29ebdea6c9ab8161577e80d6d520950
