### ISSUE TITLE
Add SQL procedures in the install.sh

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#139]
Add SQL procedures `last_audit()` and `list_running_acts()` at the end of any installation

**Comment by dzc34** [comment]
I think, it's done in [install-SQL.sh](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/tgol-resources/src/main/resources/installation/install-SQL.sh#L207) (line 207). it's it ?

```bash
add_procedures() {
    cd "${PKG_DIR}/web-app/sql-management"
    my_sql_insert PROCEDURE_ACT_list_running_acts.sql
    my_sql_insert PROCEDURE_AUDIT_last_audits.sql
    my_sql_insert PROCEDURE_AUDIT_delete_from_id.sql
    my_sql_insert PROCEDURE_CONTRACT_create.sql
}
```

**Comment by mfaure** [comment]
Effectively, already done. Closing
