### ISSUE TITLE
Site-audit in error: add "check for redirection" as possible explanation

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#146]
## Observed behaviour

Error when site-auditing http://www.gihplr.org/ (Audit has no content), where the site does exists. As a matter of fact http://www.gihplr.org/ is redirected to httpS://gihplr.org/ 

## Expected behaviour

In the error message listing possible explanations, add the case of a redirection.

## Steps to reproduce the behaviour

1. Create a project on http://www.gihplr.org/ with referential RGAA 3
1. Launch a site-audit on http://www.gihplr.org/
1. Have the audit fail and see the error page when you click on the audit

## Your configuration

https://app.asqatasun.org/ version 4.0.3

**Comment by dzc34** [comment]
files:
- [loading-error-page-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/loading-error-page-I18N_en.properties#L12)
- [synthesis-site.jsp](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/synthesis-site.jsp#L327)
- [failed-test-list.jsp](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/failed-test-list.jsp#L163)

**Comment by mfaure** [comment]
Added `category: doc` as this bug is clearly related to documentation.

Removed the following tags (with explanation for each of them):

* `category UI`: is meant for design, screen creation or front-end stuff, which is not the case here
* `need discussion`: nope we are all OK about this issue, just needs to be done :)
* `type enhancement`: `type xyz` tags are meant to be mutually exclusives, as it is a bug it can't be an enhancement. For the record, bugs need to be fixed first (must have), whereas enhancement can be done one day (nice to have)
