### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#15]
... following [Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by dzc34** [comment]
commit 5a21b60592742c9e5ef99259de3f6b4a22df3fdf

**Comment by mfaure** [comment]
Get inspired by the [Atom's Contributing file](https://github.com/atom/atom/blob/master/CONTRIBUTING.md), that is really well crafted.

**Comment by mfaure** [comment]
Done 8d623a366cb6278ef25b41bde6542cb82180579e
