### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by RyDroid** [Asqatasun/Asqatasun#158]
Hi.

It is a "feature" proposition. There is no Debian package and even no way to build one. It would be great to have a way to build one and submit it to Debian to install this program more easily.

Regards.

**Comment by dzc34** [comment]
in french: 

je bascule en français, car c’est plus rapide pour moi.
En 2 mots, c’est une bonne idée mais pas si simple que cela : 

- pour une intégration dans les dépôts officiels, cela risque d’être compromis au niveau d’1 dépendance (la version Firefox ESR) car il semble qu’il soit interdit d’installer des binaires sans passer par un paquet .deb
- pour un usage simplifié de l’installation, sans passé par les dépôts officiels, cela reste une bonne idée plutôt pratique.

Toutefois, il y a actuellement 2 ou 3 trucs qui cloche : j’ai séparé certains scripts SQL (pré-requis, création DB vide, installation des tables) et certaines images Docker ne build plus correctement. Il faut que je vérifie ce que j’ai fait. De la même manière, mes modifications ont dû casser la partie Ansible, mais je n’ai pas assez d’expérience avec Ansible pour vérifier cette partie.

Si tu sais faire ce genre de chose (.deb d'une application java), je te propose un 1er challenge un  poil moins ambitieux mais fort utile pour le projet [Contrast-Finder](https://github.com/Asqatasun/Contrast-Finder). L'avantage de commencer par là, est de nous faire une 1er expérience avec les .deb avant d'attaquer du plus contraignant.

Là, c’est plutôt simple (1 point war et 2 dépendances : tomcat et libspring-instrument-java). Et pour l’intégration au dépôt officiel, il ne devrait pas y avoir de point bloquant. La documentation est ici : 
https://github.com/Asqatasun/Contrast-Finder/tree/develop/documentation/en/10_Install_doc

**Comment by RyDroid** [comment]
- Il est effectivement interdit d'installer un binaire sans passer par un paquet. Debian utilise la version ESR de Firefox, et pourquoi y aurait il besoin d'une version spéciale de Firefox ?
- J'ai très peu d’expérience dans le packaging Debian, mais je peux essayer, et cela me permettra justement d’acquérir de l’expérience.

**Comment by mfaure** [comment]
> Il est effectivement interdit d'installer un binaire sans passer par un paquet. Debian utilise la version ESR de Firefox, et pourquoi y aurait il besoin d'une version spéciale de Firefox ?

Parce qu'il faut la version 34.x, sur les suivantes les API changent toutes les 2 ou 3 versions

> J'ai très peu d’expérience dans le packaging Debian, mais je peux essayer, et cela me permettra justement d’acquérir de l’expérience.

Cool ! Je t'invite à commencer par [Contrast-Finder](https://github.com/Asqatasun/Contrast-Finder), qui est plus light et un excellent point de départ pour le packaging (pour ensuite revenir sur Asqatasun off course ;) )

**Comment by dzc34** [comment]
ressources en français :
- https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.fr.pdf
- https://doc.ubuntu-fr.org/tutoriel/creer_un_paquet
- http://alp.developpez.com/tutoriels/debian/creer-paquet/
- https://openclassrooms.com/courses/creer-un-paquet-deb

**Comment by dzc34** [comment]
@RyDroid 
j'ai ajouté ta PR dans le dépôt git de Contrast-Finder sur une branche dédié **debian**
- https://github.com/Asqatasun/Contrast-Finder/tree/debian/debian
- https://github.com/Asqatasun/Contrast-Finder/issues/81

je ferme ta PR et cette issue.
nous pourrons la ré-ouvrir quand nous aurrons déjà pris un peu d’expérience avec Contrast-Finder et trouvé une solution élégante avec la version ESR Firefox.

**Comment by dzc34** [comment]
added to #175
