### ISSUE TITLE
Add tests with checkstyle

### ISSUE THREAD

**Issue by RyDroid** [Asqatasun/Asqatasun#159]
Hi.

To have a consistent source code, it would be useful to use [checkstyle](http://checkstyle.sourceforge.net/) and execute it through Travis CI. It is free/libre software and [available in Debian](https://packages.debian.org/stable/checkstyle).

Regards.

**Comment by dzc34** [comment]
By adding it to the `pom.xml` ? 
http://maven.apache.org/plugins/maven-checkstyle-plugin/

**Comment by RyDroid** [comment]
It could be an option. It can be also used through command line, this is how I used it as I never used Maven.

**Comment by dzc34** [comment]
How do you  execute it through Travis CI ?

**Comment by RyDroid** [comment]
Like that for example: `checkstyle -c checkstyle.xml -r src/ -f plain` https://gitlab.com/RyDroid/PepperCarrotDownloader/commit/faeb365980ba12f7723ba61e075e87c94585461b (I call indirectly checkstyle through a makefile in GitLab CI for this project)

**Comment by mfaure** [comment]
-> travis.yml

**Comment by dzc34** [comment]
To use checkstyle in travis, you may need to change the JDK version:
> "Since Checkstyle 7, some users have been unable to continue upgrading to newer versions of the utility because of the new JDK 1.8 compile requirement. The development team doesn't have the resources to keep updating the utility for older JDKs for those that can't work with the latest version. "  http://checkstyle.sourceforge.net/#Backport

> Travis CI provides OpenJDK 6, OpenJDK 7, Oracle JDK 7, and Oracle JDK 8. Sun JDK 6 is not provided, because it is EOL as of November 2012. OpenJDK 8 is available on our Trusty images, specify dist: trusty to make use of it. https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

https://github.com/Asqatasun/Asqatasun/blob/develop/.travis.yml#L3

**Comment by RyDroid** [comment]
@dzc34 It may also be possible to use an old version of checkstyle compatible with JDK7. A jar with dependencies included could be used, it is not clean but it would do the work if supporting JDK8 takes time.

**Comment by dzc34** [comment]
Done for Contrast-Finder with maven-plugin.
Thank @RyDroid for this idea !

- documentation
https://github.com/Asqatasun/Contrast-Finder/tree/develop/documentation/en/30_Contributor_doc#checkstyle
- build
https://github.com/Asqatasun/Contrast-Finder/blob/develop/pom.xml#L92
- report
https://github.com/Asqatasun/Contrast-Finder/blob/develop/pom.xml#L191

At this time, I think maven-plugin, it's a good start for us.
After, we could ugrading the process with Travis or Gitlab CI.

PR is welcome for Asqatasun !

**Comment by mfaure** [comment]
by the way, I think it becomes relevant to think moving to Gitlab and leverage Gitlab-CI, much more opensource oriented and far better integrated :)

**Comment by dzc34** [comment]
fixed #198  
with maven-plugin
