### ISSUE TITLE
Mysql 5.7 compatibility issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by solael** [Asqatasun/Asqatasun#167]
## Observed behaviour
Installed Asqatasun and Asqatasun-Runner with Jenkins Plugin on one Ubuntu 16.04 host. Installed the default mysql-server (**5.7** for the moment). 

Asqatasun Webapp works as expected but Asqatasun-Runner had problems when it tried to connect to MySQL database.

MySQL Error : 

```
2017-08-07T09:10:44.354438Z 13 [Note] Aborted connection 13 to db: 'asqatasun' user: 'asqatasun' host: 'localhost' (Got an error reading communication packets)
2017-08-07T09:10:44.354693Z 12 [Note] Aborted connection 12 to db: 'asqatasun' user: 'asqatasun' host: 'localhost' (Got an error reading communication packets)
```
the error maybe due to an configuration issue(configuration file structure change between MySQL 5.5 and MySQL 5.7) or an implementation bug in Asqatasun.

## Expected behaviour
Asqatasun-Runner should be able to execute MySQL queries as Asqatasun Web-app did.

## Steps to reproduce the behaviour
Follow the documentation to install Asqatasun and Asqatasun-Runner. Install at the same time MySQL-server, tomcat7, openjdk-8 and Jenkins...

## Your configuration

* Asqatasun version (in the footer of any webpage) -->4.0.3
* Using Docker image ? -->no

**Comment by solael** [comment]
## Workaround
Manually install MySQL 5.5
http://www.processio.com/install-mysql-5-5-5-6-ubuntu-16-04-xenial/

**Comment by dzc34** [comment]
the last release `4.1.0-rc.4` use by default Ubuntu 18.04.
