### ISSUE TITLE
Ansible - Seems to be a syntax error (ansible 2.4.2.0)

### ISSUE THREAD

**Issue by Fizzymatt** [Asqatasun/Asqatasun#186]
https://github.com/Asqatasun/Asqatasun/blob/82ac5327414ac78b07226afb06682271572cdc7f/ansible/asqatasun/tasks/main.yml#L31

**Issue**
Ansible 2.4.2.0 throws the following error for this task:

`TASK [asqatasun : Install the Asqatasun Prerequisites] *************************
failed: [asqatasun] (item=[u'asqatasun_debian_pkgs']) => {"changed": false, "item": ["asqatasun_debian_pkgs"], "msg": "No package matching 'asqatasun_debian_pkgs' is available"}`

**Solution**
The following change seems to fix the issue:

`with_items: "{{ asqatasun_debian_pkgs }}"`

**Comment by dzc34** [comment]
Hi @Fizzymatt, 

Thank you very much for taking to time to provide us with feedback !
Can you tell us which version you use : RELEASE (4.x.x) or develop version ?

**Comment by Fizzymatt** [comment]
Hi @dzc34,

It's the develop version.

Thanks :)

**Comment by dzc34** [comment]
No time to test Ansible on 4.x versions. Version 5.0-SNAPSHOT, currently on the develop branch, changes a lot the installation process. 

We will have to either delete the ansible folder or redo it entirely.
