### ISSUE TITLE
Status of next release

### ISSUE THREAD

**Issue by MIams-REISys** [Asqatasun/Asqatasun#188]
There hasn't been a release since August 2016.   Are there plans for a next one?  Can we consider the development branch suitable for production use?

Also development has slowed.  Do you consider Asqatasun mostly feature complete or is it just an issue of teams available developer time?

**Comment by mfaure** [comment]
Hi @MIams-REISys, yes there are plans for a next release but as usual in libre software, it will be shipped when it's ready :)

Few more informations: 

* Differences between dev and stable is not significant for the end-user (most of commits are related to technical stuff to ease the maintainers' life).
* Dev can be safely used in production, while adding a bit of overhead for next maintenance release.
* There are few contributors, so going forward is slow and sometimes painful.
* In the meantime, the stable release is rather feature complete.

Hope this helps !
