### ISSUE TITLE
UI: Expand All should also expand details of all the tests

### ISSUE THREAD

**Issue by selfthinker** [Asqatasun/Asqatasun#201]
## Observed behaviour

It is difficult and time-consuming to get to the single results.

Every single result is always hidden behind another click. For example, I'm not interested in reading the introductory question "Does each image (`img` tag) have an `alt` attribute?" I'm interested in what appears after I clicked on it which shows me the actual error ("The `alt` attribute is missing on the following elements :" with a list of all offending images).
![](https://user-images.githubusercontent.com/108893/36174473-56e813fe-1104-11e8-8bc5-3158e651590c.png)

## Expected behaviour

Some ideas:
* Make the "Expand all" button expand really everything and not just the questions without the answers.
* Or expand everything by default, don't hide anything.
* Or even completely remove the questions as they don't add anything and are just repeated information.
* Or use the current pattern the other way around: Show the answers but hide the questions (which can then be revealed).

## Steps to reproduce the behaviour

Open any results page with errors in it.

## Your configuration

* Asqatasun version (in the footer of any webpage) --> v4.0.3 
* Using Docker image ? --> Yes and No (it's the same either way)

**Comment by dzc34** [comment]
Hi @selfthinker,
Thank you very much for taking to time to provide us with feedback !

Can you split your issue in two issues ?
It's more easy to follow the changes of each feature request you sugest.

> Using Docker image ? --> Yes and No (it's the same either way)
yes for feedback on the UI, it's the same thing. ;)

**Comment by selfthinker** [comment]
Sure, that makes sense. I actually started with two issues but the titles I could think of were too similar. I've now split them into this one and #202. Please feel free to change the titles to make more sense.

**Comment by dzc34** [comment]
what do you think, @mfaure ?

**Comment by mfaure** [comment]
Having seen #202 I understand the need. If you have only Failed and Pre-Qualified filtered, when you click on Expand All, you expect to see all details of each test.

**Comment by mfaure** [comment]
I've just update the title of this issue to reflect the idea

**Comment by dzc34** [comment]
added to #175 and closed
