### ISSUE TITLE
UI: Time-consuming to filter results

### ISSUE THREAD

**Issue by selfthinker** [Asqatasun/Asqatasun#202]
## Observed behaviour

It is difficult and time-consuming to filter to get to the most important results.

The results page always shows 4 of the 5 possible types of results. But the only really interesting types are "failed" and "pre-qualified". It is time-consuming to always have to filter the results on every page again and again to make the massive wall of detailed results below easier to read. 
![](https://user-images.githubusercontent.com/108893/36174494-67d7c970-1104-11e8-8139-c6947424e906.png)

## Expected behaviour

I would either change the default to only show "failed" and "pre-qualified" results or add a config option so either the user or the admin can change that themselves.

## Steps to reproduce the behaviour

Open any results page with errors in it.

## Your configuration

* Asqatasun version (in the footer of any webpage) --> v4.0.3
* Using Docker image ? --> Yes

**Comment by mfaure** [comment]
Really interesting feedback, thank you !

**Comment by dzc34** [comment]
@selfthinker, great idea !

5 ways:
1. change the default to only show "failed" and "pre-qualified" for all Asqatasun instances
2. same (1), but allow admin to changing this in `asqatasun.conf`
3. config option for each user: `/account-settings.html`
4. save each change in a cookie to use it in the next result
5. ask user (checbox) to save in a cookie to use it in the next result

**Comment by mfaure** [comment]
@dzc34 Option 1 (change default behavior to show only Failed and Pre-Qualified) is the good one :)

**Comment by dzc34** [comment]
in [tgol-beans-audit-result-console-form.xml](https://github.com/Asqatasun/Asqatasun/blob/a9702f779efb8eedb94d20a2163dbdf4b3fd1630/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/mvc/form/tgol-beans-audit-result-console-form.xml#L312) 
replace:
```
    <bean id="nmiCheckboxElementBuilder" class="org.asqatasun.webapp.form.builder.CheckboxElementBuilderImpl">
        <property name="value" value="NEED_MORE_INFO"/>   (...)
        <property name="selected" value="true"/>
    </bean>
```
by 
```
    <bean id="nmiCheckboxElementBuilder" class="org.asqatasun.webapp.form.builder.CheckboxElementBuilderImpl">
        <property name="value" value="NEED_MORE_INFO"/>  (...)
        <property name="selected" value="false"/>
    </bean>
```
each result page is displayed as below without having to use filters:
![selection_001ddddddddddd](https://user-images.githubusercontent.com/6709977/36339209-9356b160-13c0-11e8-9b10-2d66829b51ae.png)

**Comment by dzc34** [comment]
@selfthinker, 

in develop branch : default is changed to only show "failed" and "pre-qualified" results.

you can use it with Asqatasun docker SNAPSHOT image:
```
docker pull asqatasun/asqatasun:SNAPSHOT
docker run --name asqatasun_dev -d -p 8080:8080  asqatasun/asqatasun:SNAPSHOT
```

**Comment by dzc34** [comment]
@mfaure, I keep in mind option 5
"ask the user (checkbox) to save the filter selected in a cookie to use it in the next result"

**Comment by mfaure** [comment]
@dzc34 Great job thanks ! Option 5 is also a good one but requires more energy. This is an old idea to give users the ability to customize some settings.
