### ISSUE TITLE
Add regular automatic testing of docker images and the online demo

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#207]
## Observed behaviour
#205 Docker Hub - All the demo ones say "Your contract has expired" 

## Expected behaviour
- [ ] Add regular automatic testing of docker images (DockerHub)
- [ ] Add regular automatic testing of the online demo https://app.asqatasun.org/

**Comment by psykoterro** [comment]
Good morning,
I've looked at your problem and if I may, I think I have a better approach to the solution.
When building your Docker image an installation of your project is deleted, which blocks the creation date of the instance and then prevents using the contracts.
I think if you put a line to update this creation date in the bootstrap of your image you would no longer have to perform these tests. 
This would allow the date to be regenerated each time the docker is launched via an option, thus allowing the image to be left as it is and only modify a part by adding this date modification.

Sincerely,
Florian

**Comment by mfaure** [comment]
@dzc34 great idea isn't it ? :)
