### ISSUE TITLE
Give user insights on currently running audits

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#21]
(from a ["christmas list" topic in Asqatasun Forum](http://forum.asqatasun.org/t/nouvelles-fonctionnalites/44))

That is to say: give the user information about which step (or engine component) the audit is:
1. crawler
2. adapter
3. processor
4. consolidator
5. analyser

and ideally how many pages have already been crawled.

**Comment by dzc34** [comment]
added to #175 and closed
