### ISSUE TITLE
i18n - Standardize "project" and "contract" appelations

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#216]
## Observed behaviour
In i18n files off the webapp, 2 words (**Project** and **Contract**) are used to designate the same thing.

## Expected behaviour
replace the word **Contract** by **Project** in i18n files 
--> only in the translation / not in the key !

```
replace     edit-contract.h1=Edit the contract {0}
by          edit-contract.h1=Edit the project {0}
```

### How to test it?
```bash
# pre-requisite: 
# - git, docker, maven
# - fork  the repository on Github
git clone https://github.com/<user>/Asqatasun.git
     # instead of:   git clone https://github.com/Asqatasun/Asqatasun.git
cd Asqatasun
git checkout develop
git checkout -b fix216

# first build
./docker/build_and_run-with-docker.sh --skip-build-test --source-dir $(pwd) --docker-dir docker/SNAPSHOT-local

   # in your browser
   # http://localhost:8085/asqatasun/admin/manage-contracts.html?user=1

# next build: use [-w | --build-only-webapp]  ---> faster
./docker/build_and_run-with-docker.sh -w --skip-build-test --source-dir $(pwd) --docker-dir docker/SNAPSHOT-local

# commit / push  + PR (pull request on Github)
git add .
git commit -m "#216 / i18n FR - Updated delete-audits-I18N_fr.properties file"
git push origin fix216
```
### edit-contract
- in your browser:  
`http://localhost:8085/asqatasun/admin/manage-contracts/edit-contract.html?cr=3`
  - [x] [edit-contract-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/edit-contract-I18N_en.properties)
  - [x] [edit-contract-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/edit-contract-I18N_fr.properties)
  - [x] [edit-contract-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/edit-contract-I18N_es.properties)
  - [ ] [edit-contract-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/edit-contract-I18N_de.properties)

### add-contract
- in your browser:  
 `http://localhost:8085/asqatasun/admin/manage-contracts/add-contract.html?user=1`
 `http://localhost:8085/asqatasun/admin/add-contract.html`
  - [x] [add-contract-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/add-contract-I18N_en.properties)
  - [x] [add-contract-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/add-contract-I18N_fr.properties)
  - [x] [add-contract-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/add-contract-I18N_es.properties)
  - [ ] [add-contract-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/add-contract-I18N_de.properties)

### delete-audits
- in your browser:  
 `http://localhost:8085/asqatasun/admin/manage-contracts/delete-contract-audits.html?cr=3`
  - [x] [delete-audits-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-audits-I18N_en.properties)
  - [x] [delete-audits-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-audits-I18N_fr.properties)
  - [x] [delete-audits-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-audits-I18N_es.properties)
  - [ ]  [delete-audits-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-audits-I18N_de.properties)

### manage-contracts + admin

- in your browser:  
`http://localhost:8085/asqatasun/admin/manage-contracts.html?user=1`
`http://localhost:8085/asqatasun/admin.html`
  - admin
    - [x] [admin-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/admin-I18N_en.properties)
    - [x] [admin-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/admin-I18N_fr.properties)
    - [x] [admin-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/admin-I18N_es.properties)
    - [ ] [admin-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/admin-I18N_de.properties)
  - manage-contracts
    - [x] [manage-contracts-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/manage-contracts-I18N_en.properties)
    - [x] [manage-contracts-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/manage-contracts-I18N_fr.properties)
    - [x] [manage-contracts-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/manage-contracts-I18N_es.properties)
    - [ ] [manage-contracts-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/manage-contracts-I18N_de.properties)

### delete-contract
- in your browser:  
`http://localhost:8085/asqatasun/admin/manage-contracts/delete-contract.html?cr=3`
  - [x] [delete-contract-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-contract-I18N_en.properties)
  - [x] [delete-contract-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-contract-I18N_fr.properties)
  - [x] [delete-contract-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-contract-I18N_es.properties)
  - [ ] [delete-contract-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/delete-contract-I18N_de.properties)

### contract-page
- in your browser:  
`http://localhost:8085/asqatasun/home/contract.html?cr=3` (see the `title` tag in the `head` tag)
  - [x] [contract-page-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/contract-page-I18N_en.properties)
  - [x] [contract-page-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/contract-page-I18N_fr.properties)
  - [x] [contract-page-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/contract-page-I18N_es.properties)
  - [ ] [contract-page-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/contract-page-I18N_de.properties)

### home-page
- in your browser:  
`http://localhost:8085/asqatasun/home/contract.html?cr=3`
  - [x] [home-page-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/home-page-I18N_en.properties)
  - [x] [home-page-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/home-page-I18N_fr.properties)
  - [x] [home-page-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/home-page-I18N_es.properties)
  - [ ] [home-page-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/home-page-I18N_de.properties)

and many others:
![](https://user-images.githubusercontent.com/6709977/38398416-b6ccf44e-3943-11e8-8761-1b8d5c7d8ebc.png)

### audit-in-progress-page
  - [x] [audit-in-progress-page-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-in-progress-page-I18N_en.properties)
  - [x] [audit-in-progress-page-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-in-progress-page-I18N_fr.properties)
  - [x] [audit-in-progress-page-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-in-progress-page-I18N_es.properties)
  - [ ] [audit-in-progress-page-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-in-progress-page-I18N_de.properties)

### audit-set-up
  - [x] [audit-set-up-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-set-up-I18N_en.properties)
  - [x] [audit-set-up-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-set-up-I18N_fr.properties)
  - [x] [audit-set-up-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-set-up-I18N_es.properties)
  - [ ] [audit-set-up-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/audit-set-up-I18N_de.properties)

### greedy-audit
  - [x] [greedy-audit-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/greedy-audit-I18N_en.properties)
  - [x] [greedy-audit-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/greedy-audit-I18N_fr.properties)
  - [x] [greedy-audit-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/greedy-audit-I18N_es.properties)
  - [ ] [greedy-audit-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/greedy-audit-I18N_de.properties)

### parameters
  - [x] [parameters-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/parameters-I18N_en.properties)
  - [x] [parameters-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/parameters-I18N_fr.properties)
  - [x] [parameters-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/parameters-I18N_es.properties)
  - [ ] [parameters-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/parameters-I18N_de.properties)

### scenario-management
  - [x] [scenario-management-I18N_en.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/scenario-management-I18N_en.properties)
  - [x] [scenario-management-I18N_fr.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/scenario-management-I18N_fr.properties)
  - [x] [scenario-management-I18N_es.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/scenario-management-I18N_es.properties)
  - [ ] [scenario-management-I18N_de.properties](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/resources/i18n/scenario-management-I18N_de.properties)

**Comment by Haradwaith** [comment]
Working on !

**Comment by mfaure** [comment]
@Haradwaith please open a pull request with your code (even if it is not tested, someone else can do that). Prefix the name of your PR with WIP so that people understand this is Work In Progress.

Thanks !

**Comment by Haradwaith** [comment]
Working on !
