### ISSUE TITLE
Outdated dependency: markdown-page-generator-plugin (2.1.0 instead of 2.0.1)

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#218]
# Observed behaviour
Outdated dependency: **markdown-page-generator-plugin**

## Expected behaviour
-  upgrade   markdown-page-generator-plugin (2.1.0 instead of 2.0.1)
   -  https://github.com/walokra/markdown-page-generator-plugin
   - https://github.com/walokra/markdown-page-generator-plugin/commits/2.1.0

## File
[pom.xml](https://github.com/Asqatasun/Asqatasun/blob/develop/pom.xml#L81)

### How to test it?
```bash
# pre-requisite: 
# - git, maven
# - fork  the repository on Github
git clone https://github.com/<user>/Asqatasun.git
     # instead of:   git clone https://github.com/Asqatasun/Asqatasun.git
cd Asqatasun
git checkout develop
git checkout -b fix218

cd documentation
mvn clean install    
    # see ./target/doc_html/

# commit / push  + PR (pull request on Github)
git add .
git commit -m "Fixed #218  - Upgraded markdown-page-generator-plugin (2.1.0 instead of 2.0.1)"
git push origin fix218
```

**Comment by allrib** [comment]
I like to take up this :)
