### ISSUE TITLE
Outdated dependency: mysql-connector-java (5.1.46 instead of 5.1.15)

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#221]
## Observed behaviour
Outdated dependency: **mysql-connector-java**

## Expected behaviour
upgrade mysql-connector-java to 5.1.46 (or 6.0.6 or 8.0.9-rc) instead of 5.1.15
- https://github.com/mysql/mysql-connector-j
- https://dev.mysql.com/doc/connector-j/5.1/en/
- https://mvnrepository.com/artifact/mysql/mysql-connector-java

## File
[pom.xml](https://github.com/Asqatasun/Asqatasun/blob/develop/pom.xml#L662)

### How to test it?
```bash
# pre-requisite: 
# - git, maven
# - fork  the repository on Github
git clone https://github.com/<user>/Asqatasun.git
     # instead of:   git clone https://github.com/Asqatasun/Asqatasun.git
cd Asqatasun
git checkout develop
git checkout -b fix221

# first build (with or whitout --skip-build-test option)
./docker/build_and_run-with-docker.sh  --source-dir $(pwd) --docker-dir docker/SNAPSHOT-local

   # in your browser
   # http://localhost:8085/asqatasun/

# commit / push  + PR (pull request on Github)
git add .
git commit -m "Fixed #221  - Upgraded  mysql-connector-java (5.1.46 instead of 5.1.15)"
git push origin fix221
```

**Comment by Mickaeldicurzio** [comment]
i'm take it

**Comment by mfaure** [comment]
Fixed by https://github.com/Asqatasun/Asqatasun/pull/224
