### ISSUE TITLE
use a PostgreSQL database

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#237]
## Observed behaviour
a user query (in french)
https://forum.asqatasun.org/t/base-de-donnees-postgresql-pour-asqatasun/474

**Comment by dzc34** [comment]
-  [Asqatasun configuration file](https://github.com/Asqatasun/Asqatasun/blob/a9702f779efb8eedb94d20a2163dbdf4b3fd1630/web-app/tgol-resources/src/main/resources/conf/asqatasun.conf#L31)
- [SQL files for PostgreSQL](https://github.com/search?utf8=%E2%9C%93&q=repo%3AAsqatasun%2FAsqatasun+extension%3Apsql&type=Code&ref=advsearch&l=&l=)

**Comment by mfaure** [comment]
To adapt a DDL from MariaDB / Mysql to Postgresql, [PGLoader](https://pgloader.io/) is an exceptional friend :)

**Comment by jkowalczyk** [comment]
Can you give it a try? from an existing db? I tried to use it but it didn't work as expected

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
