### ISSUE TITLE
UX - Bookmarlet or browser extension to launch audit on current page

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#24]
(from a ["christmas list" topic in Asqatasun Forum](http://forum.asqatasun.org/t/nouvelles-fonctionnalites/44))

Have a bookmarlet (or Firefox Extension) to audit the currently browsed page. All following informations being customisable:
- URL of the Asqatasun server (i.e. be able to use the one on my server, or if I don"t have server, the one in Docker on my workstation)
- type of referential (SEO / a11y) + level

**Comment by dzc34** [comment]
added to #175 and closed
