### ISSUE TITLE
Docker fails to run mysql

### ISSUE THREAD

**Issue by brasilikum** [Asqatasun/Asqatasun#242]
## Observed behaviour

```
docker run --name asqatasun  -p 8080:8080  asqatasun/asqatasun
 * Starting MySQL database server mysqld
   ...fail!
tail: cannot open '/var/log/tomcat7/catalina.out' for reading: No such file or directory
tail: cannot open '/var/log/asqatasun/asqatasun.log' for reading: No such file or directory
```

## Expected behaviour
It should start up just fine

## Steps to reproduce the behaviour
```
docker run --name asqatasun  -p 8080:8080  asqatasun/asqatasun
```

## Your configuration

* Asqatasun version (in the footer of any webpage) -->
* Using Docker image ? -->
Yes, 
version 4.0.0

**Comment by lahaxearnaud** [comment]
same for me on mac os

Docker Version: 18.03.1-ce-mac65 (24312)

**Comment by dzc34** [comment]
hi @brasilikum,
hi @lahaxearnaud,

if you always have this problem, 
you can report it in your forum:
https://forum.asqatasun.org/
