### ISSUE TITLE
Provide a new representation of the Asqatasun meter

### ISSUE THREAD

**Issue by jkowalczyk** [Asqatasun/Asqatasun#246]
The asqatasun meter should be a grade (A-B-C-D-E-F) instead of a percentage mark

**Comment by dzc34** [comment]
Maybe also make more visible the difference between the rules processed by Asqatasun and all the rules in the referential?

**Comment by jkowalczyk** [comment]
Can you describe a bit more what you have in mind?

**Comment by dzc34** [comment]
PR #248 is merged
