### ISSUE TITLE
TRAVIS Remove deploy target

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#249]
## Observed behaviour

Travis fails because of the `deploy` target that uses a no more existant FTP.

## Expected behaviour

No Travis fail :)

**Comment by dzc34** [comment]
it's `http://binaries.asqatasun.org/asqatasun-*` ?

**Comment by mfaure** [comment]
This host no longer exists.

It was used by the Docker Images but all of this will be useless as we are... #MovingToGitLab :stuck_out_tongue:
