### ISSUE TITLE
localhost URLs should not be blocked

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#25]
(from a [bug report on Asqatasun Forum](http://forum.asqatasun.org/t/bug-liste-avant-creation-dissues-dans-github/45))

Local URLs such as `http://localhost/` should be authorized.

**Comment by dzc34** [comment]
and http://localhost:8081

**Comment by dzc34** [comment]
fix here https://github.com/Asqatasun/Asqatasun/commit/e7012329f872bee70557e2f5e2064406bee35056
