### ISSUE TITLE
how install, or demo, or screenshot

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#26]
Hello, i new here.
And interested about this project, but not see documentaion how install, or demo, or screeshout.
Can some one give manual, what server configuration i need, and some install manual?

**Comment by dzc34** [comment]
For testing Asqatasun, you can use docker with this documentation
https://github.com/Asqatasun/Asqatasun/blob/develop/docker/single-container/README.md

But to date, it does not work
The team works for fix it.

**Comment by gwynnbleiidd** [comment]
Thanks, I will try on the local computer.
I hope it will turn out to launch and with the future I will be able to help with development if I correctly understood assignment of a product :)

**Comment by dzc34** [comment]
now it works

for testing Asqatasun, you can use docker with this documentation
https://github.com/Asqatasun/Asqatasun/blob/develop/docker/single-container/README.md
