### ISSUE TITLE
Add hostname when error message is sent

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#268]
## Observed behaviour

When an audit fails, an email is fired. This email doesn't provide any information about the host sending the email. This may be misleading when one manages more than one Asqatasun instance.

Keyword to find suitable file in code : `krash-admin-content`

## Expected behaviour

Have the "error email" providing the name of the host which is sending the email.

## Steps to reproduce the behaviour

Try to audit `http://kfzrllskdflsdkfsldkfslkfdnlfksdnflsdknfsl/`

**Comment by jkowalczyk** [comment]
Templates can be found in the email-content-I18N bundle behind `krash-admin-subject` and `krash-admin-content` properties.

The ```#host``` key in the translation is replaced by the result of the ```InetAddress.getLocalHost().getHostName()``` method
