### ISSUE TITLE
Contract creation: verify at least one referential is selected

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#27]
(from a [bug report on Asqatasun Forum](http://forum.asqatasun.org/t/bug-liste-avant-creation-dissues-dans-github/45))

In the admin pages, when creating a contract: verify at least one referential is selected (instead error 500).

**Comment by dzc34** [comment]
see  [webapp/validator/CreateContractFormValidator.java](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/validator/CreateContractFormValidator.java)
