### ISSUE TITLE
Contract creation: forbid contract without URL and with site-audit enabled

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#28]
(from a [bug report on Asqatasun Forum](http://forum.asqatasun.org/t/bug-liste-avant-creation-dissues-dans-github/45))

Contract creation: add a verification so that creating a contract:
1. without URL and
2. with site-audit activated

... should not be possible (instead error 500 when launching a site audit)

**Comment by dzc34** [comment]
see : [webapp/validator/CreateContractFormValidator.java](https://github.com/Asqatasun/Asqatasun/blob/develop/web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/validator/CreateContractFormValidator.java#L227)
