### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [Asqatasun/Asqatasun#288]
Hi
The following lines have cryptographic API misuses. <br> File name => engine/asqatasun-api/src/main/java/org/asqatasun/util/MD5Encoder.java: Line number => 79: API name => MessageDigest:<BR> File name => engine/asqatasun-api/src/main/java/org/asqatasun/util/MD5Encoder.java: Line number => 77: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by dzc34** [comment]
@mhp0rtal = bot 
`July 2, 2019 "Opened 918 issues in 892 repositories"`
see also:  https://github.com/mob41/broadlink-java-api/issues/22
