### ISSUE TITLE
Build fail: "javax.xml.bind.annotation does not exist" (openjdk 11, maven 3.6)

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#289]
## Observed behaviour

error: `package javax.xml.bind.annotation does not exist`

```
[INFO] asqatasun 4.1.0-SNAPSHOT ........................... SUCCESS [  2.147 s]
[INFO] engine 4.1.0-SNAPSHOT .............................. SUCCESS [  0.029 s]
[INFO] commons-entity 4.1.0-SNAPSHOT ...................... SUCCESS [  1.403 s]
[INFO] commons-entity-jpa 4.1.0-SNAPSHOT .................. SUCCESS [  0.473 s]
[INFO] asqatasun-api 4.1.0-SNAPSHOT ....................... FAILURE [  1.363 s]
(...)
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project asqatasun-api: Compilation failure: Compilation failure: 
[ERROR] engine/asqatasun-api/src/main/java/org/asqatasun/service/ProcessorService.java:[25,33] package javax.xml.bind.annotation does not exist
[ERROR] engine/asqatasun-api/src/main/java/org/asqatasun/service/ProcessorService.java:[34,2] cannot find symbol
[ERROR]   symbol: class XmlTransient
```

## Expected behaviour
```
[INFO] asqatasun-api 4.1.0-SNAPSHOT ....................... SUCCESS 
```

## Steps to reproduce the behaviour
```
cd ~
mv .m2 .m2_backup
git clone ...
cd Asqatasun
mvn clean install
```

##  Configuration

```
mvn --version
	Apache Maven 3.6.0
	Maven home: /usr/share/maven
	Java version: 11.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
	OS name: "linux", version: "4.15.0-54-generic", arch: "amd64", family: "unix"

java -version
	openjdk version "11.0.3" 2019-04-16
```

**Comment by dzc34** [comment]
``` 
java.xml.bind (JAXB)
    Java 8 - OK
    Java 9 - DEPRECATED
    Java 10 - DEPRECATED
    Java 11 - REMOVED
```
source: https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist/52502208#52502208
```
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.1</version>
</dependency>

```
source: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/52872160#52872160

**Comment by Mesrar** [comment]
Add this dependency to your pom.xml can fix the issues :+1: 

`       <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>2.3.3</version>
        </dependency>`

**Comment by mayur5643** [comment]
Great job Mesrar. my error is solved now. Thanks.

**Comment by weifengze** [comment]
thanks https://github.com/Asqatasun/Asqatasun/issues/289#issuecomment-665690850

**Comment by SisFrio97** [comment]
Hola colegas soy rpincipiante y restaure un programa algo viejo perome maraca erro en muchas partes y tienen relacion con esto. me pueden ayudar

codigo..

package mx.sat.cfdi;

import jakarta.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


y me aparece este error :c ayuda
![Captura de pantalla 2024-01-23 162538](https://github.com/Asqatasun/Asqatasun/assets/82838775/f40a7461-dde2-40e4-a3e2-336781a9b1ed)

warning: [options] bootstrap class path not set in conjunction with -source 8
C:\Users\Usuario\Desktop\sofia sistems pract\Servicios-main\src\Cfdi33\CMetodoPago.java:12: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlEnum;
/
![Captura de pantalla 2024-01-23 162538](https://github.com/Asqatasun/Asqatasun/assets/82838775/f40a7461-dde2-40e4-a3e2-336781a9b1ed)
