### ISSUE TITLE
Use selenium IDE to create and replay scenario

### ISSUE THREAD

**Issue by jkowalczyk** [Asqatasun/Asqatasun#294]
## Expected behaviour
We don't use se-builder anymore but selenium ide instead

To do so, we need to use the [selenese runner java](https://github.com/vmi/selenese-runner-java)  library to interpret the scenario.

**Comment by jkowalczyk** [comment]
Will close all related issues
#305 

#303 

#302

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
