### ISSUE TITLE
MySQL fails to start when using DockerHub image

### ISSUE THREAD

**Issue by mikesir87** [Asqatasun/Asqatasun#297]
## Observed behaviour

When starting the `asqatasun/asqatasun:latest` container from DockerHub and using the `overlay2` storage driver (which is default in most installations), mysql fails to start, which then causes everything else to fail. Most likely, this is what #242 was seeing too.

## Expected behaviour

MySQL starts.

## Steps to reproduce the behaviour

Use a current version of Docker and ensure the overlay2 storage driver is being used (use `docker system info` to verify).

## References
- https://github.com/docker/for-linux/issues/72

## Fix

To fix this (per the reference above), you need to force the storage driver to move all of the mysql files into the container's scratch space. Simply touching the files causes this to happen.

I'd gladly send a PR, but it's hard to tell what Dockerfile is being used when publishing to DockerHub. Updating the `CMD` to the following works:

```dockerfile
CMD  find /var/lib/mysql -type f -exec touch {} \;  && \
     service mysql start                            && \
     sleep   5                                      && \
     service xvfb start                             && \
     service tomcat7 start                          ;  \
     tail -f /var/log/tomcat7/catalina.out
```

**Comment by dzc34** [comment]
hi @mikesir87 ,

I'm not reproducing this bug.
see below the command lines used and the log display.
```bash
# use a current version of Docker and ensure the overlay2 storage driver is being used
docker system info
            Server Version: 19.03.2
            Storage Driver: overlay2
            Operating System: Ubuntu 18.04.3 LTS
            Architecture: x86_64

# remove all docker containers based on asqatasun/asqatasun:latest
docker ps -a | awk '{ print $1,$2 }' | grep 'asqatasun/asqatasun' | awk '{print $1 }' | xargs -I {} docker stop {}
docker ps -a | awk '{ print $1,$2 }' | grep 'asqatasun/asqatasun' | awk '{print $1 }' | xargs -I {} docker rm {}

# remove docker image
docker image rm asqatasun/asqatasun

# starting the asqatasun/asqatasun:latest container from DockerHub 
docker pull asqatasun/asqatasun
docker run --name asqatasun_last -p 127.0.0.1:8080:8080  asqatasun/asqatasun

            * Starting MySQL database server mysqld
            ...done.
            * Checking for tables which need an upgrade, are corrupt or were not closed cleanly.
            * Starting Tomcat servlet engine tomcat7
             (....)
            ==> /var/log/asqatasun/asqatasun.log <==
            INFO  org.springframework.web.servlet.DispatcherServlet  - FrameworkServlet 'tgol-web-app': initialization completed in 3383 ms

```
-------------------------------
The DockerFile used by the asqatasun/asqatasun:latest image from DockerHub 
https://github.com/Asqatasun/Asqatasun/blob/v4.0.3/docker/single-container/Dockerfile

This file was moved (on develop branch and on the pre-releases of master branch) here:
https://github.com/Asqatasun/Asqatasun/blob/develop/docker/RELEASE/Dockerfile

I also don't reproduce this bug by locally building the Dockerfile file 
see below the command lines used.
```bash
git clone https://github.com/Asqatasun/Asqatasun.git
cd Asqatasun
docker/build_and_run-with-docker.sh        \
                         -s ${PWD}         \
                         -d docker/RELEASE \
                         --skip-build      \
                         --skip-copy       \
                         --only-localhost          

# same as
git clone https://github.com/Asqatasun/Asqatasun.git
cd Asqatasun/docker/RELEASE
docker build -t asqatasun/asqatasun:2019-09-07 .
docker run -p 127.0.0.1:8085:8080 --name asqa  asqatasun/asqatasun:2019-09-07
```

-------------------------------
Can you provide more information like command lines used and logs ?

**Comment by dzc34** [comment]
Not reproduced  bug and lack of information on the occurrence of the problem.
