### ISSUE TITLE
Do we record scenarios in SE Builder or Selenium IDE?? 

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#298]
the PDF documentation still points to Selenium Builder.. but on one of the issues it was mentioned you dont use SE builder anymore -- rather we are asked to use selenium ide??

Let me know - thank you...

## Your configuration

* Asqatasun version (in the footer of any webpage) -->
* Using Docker image ? -->

**Comment by dzc34** [comment]
some info in french:
https://forum.asqatasun.org/t/audits-scenario-extension-sebuilder-introuvable/599
