### ISSUE TITLE
Remove phantomJsDriver and replace by firefox headless 

### ISSUE THREAD

**Issue by jkowalczyk** [Asqatasun/Asqatasun#305]
## Observed behaviour
To avoid to use an xvfb Xserver, an implemention using phantomJsDriver can be used  instead of the firefox one.

## Expected behaviour
Remove the phantomJsDriver implementation and make the scenario loader compatible with firefox headless. 
Probably need to upgrade selenium and rewrite a scenario module loader

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
