### ISSUE TITLE
The relaunch button is broken on the page result page

### ISSUE THREAD

**Issue by jkowalczyk** [Asqatasun/Asqatasun#323]
## Observed behaviour
On the result page, clicking on the relaunch button displays the loader but nothing happens

## Expected behaviour
An audit should be relaunched

## Steps to reproduce the behaviour
Display the result page of an audit and try to click the button

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
