### ISSUE TITLE
Upgrade crawler module

### ISSUE THREAD

**Issue by mackristof** [Asqatasun/Asqatasun#325]
remove heritix-engine from crawler module. 
use edu.uci.ics / crawler4j  / 4.4.0

**Comment by mfaure** [comment]
Welcome @mackristof! Thanks for the report, and I presume, the following PR :)

**Comment by mackristof** [comment]
thanks @mfaure. for the PR, as soon as possible ;-)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
