### ISSUE TITLE
v5 branch - Build fail: "javax.xml.bind.annotation does not exist" (openjdk 11, maven 3.6) 

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#327]
## Observed behaviour

I have these errors on the `v5` branch :
- `package javax.xml.bind.annotation does not exist`
- `cannot find symbol class XmlTransient`

```
[INFO] asqatasun 5.0-SNAPSHOT ............................. SUCCESS [  1.231 s]
[INFO] engine 5.0-SNAPSHOT ................................ SUCCESS [  0.020 s]
[INFO] asqatasun-api 5.0-SNAPSHOT ......................... FAILURE [  1.190 s]
[INFO] rule-implementation-loader 5.0-SNAPSHOT ............ SKIPPED
(...)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project asqatasun-api: Compilation failure: Compilation failure: 
[ERROR] engine/asqatasun-api/src/main/java/org/asqatasun/analyser/AnalyserService.java:[27,33] package javax.xml.bind.annotation does not exist
[ERROR] engine/asqatasun-api/src/main/java/org/asqatasun/analyser/AnalyserService.java:[33,2] cannot find symbol
[ERROR]   symbol: class XmlTransient
```
same as issue #289 "Build fail: "javax.xml.bind.annotation does not exist" (openjdk 11, maven 3.6)"

> ``` 
> java.xml.bind (JAXB)
>     Java 8 - OK
>     Java 9 - DEPRECATED
>     Java 10 - DEPRECATED
>     Java 11 - REMOVED
> ```
> source: https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist/52502208#52502208
> ```
> <dependency>
>   <groupId>javax.xml.bind</groupId>
>   <artifactId>jaxb-api</artifactId>
>   <version>2.3.1</version>
> </dependency>
> 
> ```
> source: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/52872160#52872160

## Expected behaviour
```
[INFO] asqatasun-api 5.0-SNAPSHOT ....................... SUCCESS 
```

## Steps to reproduce the behaviour
```bash
git clone ...
cd Asqatasun
git checkout develop
mvn clean install
```

## Your configuration
```bash
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-45-generic", arch: "amd64", family: "unix"
```

This works well with jdk8 
using for example https://github.com/Asqatasun/asqa.mvn/blob/master/Asqatasun/jdk-8/Dockerfile

**Comment by mfaure** [comment]
@dzc34 I think this issue is not more relevant as I merged #326 #333 and #337.

If this is true, would you please close this issue? If not could you tell us more? (thx!)

**Comment by dzc34** [comment]
@mfaure
- #333 ---->  **4.1** branch
-  #327 (this issue) ---> `develop` branch

> I have these errors on the develop branch :

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
