### ISSUE TITLE
4.1.0 Error in loading page (abbeville)

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#338]
## Observed behaviour

Audit on http://www.abbeville.fr/ leads to error page "Une erreur est survenue lors du chargement de la page"

## Expected behaviour

Be able to audit http://www.abbeville.fr/

## Steps to reproduce the behaviour

1. Grab an Asqatasun 4.1.0
1. In the project openbar A11Y RGAA3.0, select a Page audit
1. type in URL `http://www.abbeville.fr/`
1. validate

## Relevant logs

```
==> /var/log/asqatasun/asqatasun.log <== 
11-04-2020 10:09:15:185 96349758 INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - Launching audit Page on http://www.abbeville.fr/ 
11-04-2020 10:09:21:786 96356359 INFO  org.asqatasun.service.command.AbstractScenarioAuditCommandImpl  - Loading content for null 
11-04-2020 10:09:21:786 96356359 WARN  org.asqatasun.service.command.AbstractScenarioAuditCommandImpl  - Audit Status is ERROR while SCENARIO_LOADING was required  
11-04-2020 10:09:21:804 96356377 WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whileCONTENT_ADAPTING was required 
11-04-2020 10:09:21:816 96356389 WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whilePROCESSING was required 
11-04-2020 10:09:21:826 96356399 WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whileCONSOLIDATION was required 
11-04-2020 10:09:21:829 96356402 WARN  org.asqatasun.service.command.AuditCommandImpl  - Audit status isERROR whileANALYSIS was required 
11-04-2020 10:09:22:313 96356886 INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - Audit page terminated on http://www.abbeville.fr/ 

```

## Your configuration

* Asqatasun version (in the footer of any webpage) --> 4.1.0

### Other information

* This used to work on v4.0.3 (just tested)

**Comment by mfaure** [comment]
Workaround:

1. Run the audit a first time, it fails.
1. Run the audit a second time, it succeeds (!)

(I removed the tags `regression` and `bug` as I don't know how to qualify this issue for now)

Other info:

* The page is around 20Mb fat (!). Is this related?
* Is this a timeout issue? Somehow related to DNS resolving?

**Comment by dzc34** [comment]
we could close this issue?

**Comment by mfaure** [comment]
@dzc34 Not sure. Let's have some time to think about it :)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
