### ISSUE TITLE
4.1.0 - Email content is badly encoded (UTF-8)

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#341]
## Observed behaviour

Emails sent (delayed audit, audit in error...) are badly encoded.

Excerpt of log file `asqatasun.log` with `log4j.logger.org.asqatasun.emailsender=DEBUG` (example of French email with accents)

```
13-04-2020 15:03:32:518 115730 INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - success email sent to [admin@asqatasun.org] on audit n° 7 
13-04-2020 15:03:32:584 115796 DEBUG org.asqatasun.emailsender.EmailSender  - emailContent  <p>F�~C©licitations !</p> 
<p>Votre audit du projet <strong>Wikipedia SEO</strong> s'est termin�~C© avec succ�~C¨s.</p> 
<p>Les r�~C©sultats sont d�~C¨s �~C  pr�~C©sent consultables ici : <a href="http://localhost:8080/asqatasun/home/contract/audit-result.html?audit=7">http://localhost:8080/asqatasun/home/contract/audit
-result.html?audit=7</a></p> 
<p>Ne l�~C¢chez rien !<br/> 
Asqatasun</p> 
13-04-2020 15:03:32:607 115819 DEBUG org.asqatasun.emailsender.EmailSender  - emailContent from message object <p>F�~C©licitations !</p> 
<p>Votre audit du projet <strong>Wikipedia SEO</strong> s'est termin�~C© avec succ�~C¨s.</p> 
<p>Les r�~C©sultats sont d�~C¨s �~C  pr�~C©sent consultables ici : <a href="http://localhost:8080/asqatasun/home/contract/audit-result.html?audit=7">http://localhost:8080/asqatasun/home/contract/audit
-result.html?audit=7</a></p> 
<p>Ne l�~C¢chez rien !<br/> 
Asqatasun</p> 
13-04-2020 15:03:32:609 115821 DEBUG org.asqatasun.emailsender.EmailSender  - addr admin@asqatasun.org 
13-04-2020 15:03:32:658 115870 INFO  org.asqatasun.webapp.orchestrator.AsqatasunOrchestratorImpl  - Audit site terminated on https://en.wikipedia.org/
```

## Expected behaviour

* accents and special characters should be correctly encoded

## Steps to reproduce the behaviour

1. Use [Asqatasun Vagrant](https://gitlab.com/asqatasun/asqatasun-vagrant) (v4.1.0)
1. Modify `/var/lib/tomcat8/webapps/asqatasun/WEB-INF/classes/log4j.properties`, and add `log4j.logger.org.asqatasun.emailsender=DEBUG`
1. Restart tomcat
1. Run a site audit on project Wikipedia (limit to 5 pages to be quick)
1. See `/var/log/asqatasun/asqatasun.log`

(you may also actually receive the email, or configure a MailHog, result is the same: content is badly encoded.)

Note: this concerns the email content and also the email subject

## Your configuration

* Asqatasun version (in the footer of any webpage) --> 4.1.0

**Comment by jkowalczyk** [comment]
I guess the problem is more related with the encoding of the terminal

**Comment by mfaure** [comment]
Similar to https://stackoverflow.com/questions/42451930/java-mail-setting-chinese-encoding ?

**Comment by mfaure** [comment]
Other possibly related questions:

* [How to send UTF-8 encoded email body with JavaMailSenderImpl?](https://stackoverflow.com/questions/30289458/how-to-send-utf-8-encoded-email-body-with-javamailsenderimpl)
* [javax mail: UTF-8 encoding issue](https://stackoverflow.com/questions/42447635/javax-mail-utf-8-encoding-issue)

**Comment by mfaure** [comment]
I might have understood something:

* I've read somewhere that Java.util resource bundle only accept iso-8859-1 (reference to be found / verified). I also read about a tool doing some conversion stuff.
* file format of (at least) `email-content-I18N.properties` was modified re-encoded in UTF-8 after v4.0.3 (see [git log of `email-content-I18N.properties`](https://github.com/Asqatasun/Asqatasun/commits/develop/web-app/asqatasun-web-app/src/main/resources/i18n/email-content-I18N_fr.properties))
* Contrast-Finder doesn't face the issue, but neither sends email
* Content with accents is fine in JSP, maybe there some kind of conversion on the fly

What may be done:

* verify charset accepted by resource bundle  --> @jkowalczyk would you help?
* identify how JSP pages deal with accents --> @jkowalczyk would you help?
* find the "conversion tool" for resource bundle --> @mfaure 
* try to rewrite special characters (like accents) with suitable encoding only in the `email-content-*` files and test  --> @mfaure

**Comment by mfaure** [comment]
In fact, a lot of answers is given in [How to use UTF-8 in resource properties with ResourceBundle](https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle?noredirect=1).

* Confirmation that Java reads resource bundle as ISO-5589-1 (see [`load()` from Java 8 doc](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.InputStream-))
* The "conversion tool" is named `native2ascii` and is part of the JDK (package `openjdk-8-jdk-headless` on Ubuntu 18.04). And this tool was already known by @dzc34 as he wrote [i18n README.md](https://github.com/Asqatasun/Asqatasun/blob/develop/documentation/en/30_Contributor_doc/i18n/README.md)
* The default behavior of editors like Eclipe and IntelliJ need to be investigated

**Comment by mfaure** [comment]
Solution found. Implementation in progress :smile:
