### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#351]
## Observed behaviour
Error 404 on all pages of `doc.asqatasun.org`

## Expected behaviour
all pages of `doc.asqatasun.org` works fine.

## Alternative
- In the [documentation/](https://github.com/Asqatasun/Asqatasun/tree/master/documentation) directory if you cloned the repos 
-  Also included in the .tar.gz of each release

## Todo list
- [ ] reload `doc.asqatasun.org` (ping @mfaure)
- [ ] updated the README file to remove some problematic links (PDF/Epub)

**Comment by mfaure** [comment]
Thanks @dzc34! A few information on the context:

* We use to use [Gitbook](https://github.com/GitbookIO/gitbook) (the libre software) with gitbook.com  hosting the actual documentation.
* Gitbook (the company) decided to leave Gitbook the software (last update dec. 2018) and migrated the hosting offer to a proprietary solution.
* As gitbook.com hosting no longer uses libre software, we planned to move away.
* Gitbook (the company) imposed to move our documention to the proprietary offer before 2020-04-30. 
* To have more time to organize our plan to move away, we decided to use temporarily the proprietary offer. But the migration failed.
* We are now planning to host our documentation ourselves, and by the way use libre-software to create the doc, for instance [Hugo](https://github.com/gohugoio/hugo)

**Comment by sbaldwin24** [comment]
@mfaure Do you need any help migrating the documentation to Hugo or Gatsby?

**Comment by mfaure** [comment]
@sbaldwin24 Yes! Any help is warmly welcome :)

A first todo-list has been created in [Bring back doc.Asqatasun.org](https://gitlab.com/asqatasun/documentation/-/issues/1) (We also had plan to move to Gitlab, this made the opportunity to do it.)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
