### ISSUE TITLE
Docker username and password aren't working

### ISSUE THREAD

**Issue by pcolmer** [Asqatasun/Asqatasun#353]
## Observed behaviour
Try to log in with user `admin@asqatasun.org` and password `myAsqaPassword`. System reports "Invalid login and/or password. Please try again."

## Expected behaviour
Log in should be successful.

## Steps to reproduce the behaviour
Follow the instructions at https://github.com/Asqatasun/Asqatasun/tree/master/documentation/en/10_Install_doc/Docker.

## Your configuration

* Asqatasun version (in the footer of any webpage) --> 4.0.3
* Context (Docker image / Vagrant VM / plain install) ? --> Latest Docker image

**Comment by mfaure** [comment]
Thank you very much for your feedback @pcolmer Actually, you're right; here are the correct credentials : 

* login : `me@my-email.org`
* password `myAsqaPassword`

Please note this is the old credentials, this has changed in v4.1.0. 

In fact, the doc is up-to-date, but the docker image is not (yet). We will be releasing new docker images for v4.1.0 soon.

Thanks for your interest in Asqatasun and let us know how it goes !
