### ISSUE TITLE
Progress on tool for recording scenarios?

### ISSUE THREAD

**Issue by robfentress** [Asqatasun/Asqatasun#354]
Has there been any progress on supporting a different tool, such as Selenium IDE, for recording scenarios, since the currently recommended tool, SEBuilder, requires using a very old and insecure browser?  Alternately, a tool that could convert the output format of Selenium IDE to the output format of SEBuilder, would be helpful. See #298 .

**Comment by jkowalczyk** [comment]
We are currently working on it.

https://github.com/Asqatasun/Asqatasun/tree/294_Use_selenium_IDE_to_create_and_replay_scenario

**Comment by jkowalczyk** [comment]
You could start trying from a local build of this branch.

To do so, here are the requirements. 

1. You need first to download the latest est firefox version and install it locally from that page

```
cd /opt
sudo wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.9.0esr/linux-x86_64/en-US/firefox-68.9.0esr.tar.bz2
sudo tar xvf firefox-68.9.0esr.tar.bz
```

2.  Then you need to install geckodriver

```
cd /opt
sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
sudo tar xvf geckodriver-v0.26.0-linux64.tar.gz
```

3. Start a fresh mysql server 
 
```
docker run -e MYSQL_ROOT_PASSWORD=bou -e MYSQL_DATABASE=asqatasun -p 3306:3306 mysql:5

```

4. Build locally 

 ```
cd $PATH_TO_ASQATASUN_SOURCE_DIR
mvn clean install
```

5. Lauch the application (which is now spring-bootable)

```
java -Dwebdriver.firefox.bin=/opt/firefox/firefox -Dwebdriver.gecko.driver=/opt/geckodriver -jar $PATH_TO_ASQATASUN_SOURCE_DIR/web-app/asqatasun-web-app/target/asqatasun-web-app-5.0-SNAPSHOT.war --server.port=5959
```
The application is now accessible at http://localhost:5959

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
