### ISSUE TITLE
IPv6 client

### ISSUE THREAD

**Issue by fridezlucas** [Asqatasun/Asqatasun#357]
## Observed behaviour

I installed Asqatasun on a server and try to run an audit for a complete site and for a page. I got a 500 Error page. I read the logs and a saw that field "Client_Ip" was too short. (Varchar 16 for IPv4 only). 

I changed type of TGSI_ACT.Client_Ip to varchar that can contains IPv6.

## Expected behaviour

Audit is functionnal

## Steps to reproduce the behaviour

Install Asqatasun and try to run an audit (site or url page) with a IPv6 client.

## Your configuration

Asqatasun v4.1.0-rc.5

## Improvement

Can you change type of TGSI_ACT.Client_Ip for next release to support IPv6 client ?

**Comment by dzc34** [comment]
to fix in the next version?  (cc @koj / @mfaure)

**Comment by mfaure** [comment]
Great feedback @fridezlucas thank you! I think nobody ever tried IPv6. That's a great improvement for v5

**Comment by dzc34** [comment]
I replaced `Varchar 16` with `Varchar 46` in PR #368 (Asqatsun v4) and PR #370 (Asqatsun v5).

Magic number: **46**
- https://www.wireshark.org/lists/wireshark-dev/201105/msg00061.html
- https://stackoverrun.com/fr/q/10866340
- https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
- https://tools.ietf.org/html/rfc4291#section-2.2

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
