### ISSUE TITLE
v5 -  Have a default project enabled

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#362]

**Comment by jkowalczyk** [comment]
To do so, you just need to add an sql script called 
MSDB-0.0.10__AddFirstContract.sql  in [this resource directory](https://github.com/Asqatasun/Asqatasun/tree/v5/web-app/webapp-persistence/src/main/resources/sql/automated/common)  and let flyway execute it on startup

**Comment by dzc34** [comment]
```sql
MSDB-0.0.0__InitiDB.sql
MSDB-0.0.1__insertLevelAndParameters.sql
MSDB-0.0.2__insertRulesResources.sql
MSDB-0.0.3__addAw22Referential.sql
MSDB-0.0.4__insertRgaa22Referential.sql
MSDB-0.0.5__insertRgaa3Referential.sql
MSDB-0.0.6__insertSeoReferential.sql
MSDB-0.0.7__InitSiDB.sql
MSDB-0.0.8__PopulateSiDB.sql
MSDB-0.0.9__AddFirstUser.sql
MSDB-0.0.10__AddReferentials.sql
```
`0.0.10` is already used, so I'm going to add `0.0.11`

**Comment by dzc34** [comment]
@jkowalczyk, how do I create the 1st user (and his 1st contract) only if no user is present in DB?

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
