### ISSUE TITLE
Asqatasun websites  (app, forum and www) are down ---> DNS error

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#372]
## Observed behaviour
Asqatasun websites  (app, forum and www) are down. 
The DNS configuration seems to be the source of this problem.

- https://asqatasun.org
- https://app.asqatasun.org
- https://forum.asqatasun.org
- https://doc.asqatasun.org
- https://download.asqatasun.org

## While waiting for DNS configuration fix

Until the application is back online, you can [use Vagrant to run Asqatasun](https://gitlab.com/asqatasun/asqatasun-vagrant/-/tree/master/Ubuntu-18.04/Asqatasun_v4.1.0) on your computer. 

Until the documentation site is back online, you can consult [Asqatasun documentation](https://github.com/Asqatasun/Asqatasun/tree/master/documentation/en) directly on Github. 

## Expected behaviour
Asqatasun websites  (app, forum and www) are up. 
The DNS configuration works.

## To do - When the problem is solved
- add a message on this issue
- post a message on the forum
- tweet a message
- reply to the following tweets:
  - https://twitter.com/Asqatasun/status/1294208414990643200
  - https://twitter.com/locatellia1/status/1292735266675974149
  - https://twitter.com/locatellia1/status/1292753378599206912
  - https://twitter.com/locatellia1/status/1294301467650785280

**Comment by mfaure** [comment]
## Status

As of 2020-08-19 14h35 UTC+2, all websites are back:

- https://asqatasun.org
- https://app.asqatasun.org
- https://forum.asqatasun.org
- https://doc.asqatasun.org
- https://download.asqatasun.org

Post mortem is in progress.

**Comment by vaibhavshukl12** [comment]
Hi, @mfaure Hope you are doing well! 
 https://doc.asqatasun.org is still not working

**Comment by escalope** [comment]
Hello
https://doc.asqatasun.org not working here either

**Comment by mfaure** [comment]
@vaibhavshukl12 @escalope thank you for your feedback! There was typo in this DNS entry, this is fixed now.

As a side note, the documentation site is being rewritten (gitbook.io became proprietary), in the meantime all documentation itself is in the [`documentation` directory](https://github.com/Asqatasun/Asqatasun/tree/master/documentation)

**Comment by mfaure** [comment]
Communication done:

* In the forum: [*.asqatasun.org websites unavailable (aka DNS error)](https://forum.asqatasun.org/t/asqatasun-org-websites-unavailable-aka-dns-error/744)
* Twitter: [@asqatasun message on 2020-08-20](https://twitter.com/Asqatasun/status/1296498068666355715)
* Twitter: [reply from @mfaure to @locatellia1](https://twitter.com/mfaure/status/1296499388584529920)

I closed the issue. Feel free to re-open if anything goes wrong :slightly_smiling_face:
