### ISSUE TITLE
Document website is broken

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#373]
## Behaviour

The documentation website [doc.asqatasun.org](doc.asqatasun.org) is broken.

## Explanation

We used gitbook.io (an online hosting service based on gitbook, a libre software). Gitbook.io decided to drop gitbook replacing it by a proprietary software. As we didn't want to use closed source software, we dropped it.

## Solution

A new website s being recreated based on Hugo

## Workaround

All the doc is still available from the [`documentation` directory](https://github.com/Asqatasun/Asqatasun/tree/master/documentation)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
