### ISSUE TITLE
Error during site crawling due after ignoring a missing robots.txt

### ISSUE THREAD

**Issue by escalope** [Asqatasun/Asqatasun#375]
## Observed behaviour

The site https://ucm.es and https://upm.es cannot be crawled. Asqatasun returns a failure everytime (Either the domain doesn’t exist; Either the access to the site is denied by robots.txt (Link to the robots.txt file); Either the site is redirected to another domain (www.domain.com to domain.com or http://domain.com to httpS://domain.com); Or the site requires authentication)

Page audit works with both sites. 

Enabling the debug option, the generated log for asqatasun and catalina is attached. 
[catalina-log.txt](https://github.com/Asqatasun/Asqatasun/files/5126717/catalina-log.txt)
[asqatasun-log.txt](https://github.com/Asqatasun/Asqatasun/files/5126718/asqatasun-log.txt)

Things I observe:
- the robots.txt is not found, but asqatasun does not recognise the 404. I tried with wget, and it catches the 404
- the mime is not recognised, even though there is one (again recognised by wget and the developer tools in firefox)
- the robots.txt is not ignored even if one sets the heritrix parameter of calculateRobotsOnly is set to false in the config file. I read in the asqatasun doc that it is overriden. I tried to disable this, but could not find an easy way. 
- since robots cannot be found and the system seems to ignore the 404, somewhere it assumes it is ok to go on; then the "Robots prerequisite failure" is raised, aborting the crawl. I have enriched the error messages in the log to know of the connection status in case of failre. I will pull the modification if you  find this useful.

## Expected behaviour

A site report should be generated. It works with other sites, such as https://www.sitespeed.io.

## Steps to reproduce the behaviour
1. git clone the repo
2. build the docker image using the script
3. launch the site and configure a project for a site audit of any of https://ucm.es or https://upm.es
4. A failure should be triggered

## Your configuration
Latest version from the repo, but tried as well with 4.0.3 (only docker image) and official 4.1.0 (only docker image). Best results are obtained from the master branch built version.

* Asqatasun version (in the footer of any webpage) --> 4.1.1- SNAPSHOT
* Context (Docker image / Vagrant VM / plain install) ? --> DOCKER

**Comment by mfaure** [comment]
@escalope thank you very much for your extensive bug report! We're digging into this

**Comment by escalope** [comment]
Thanks, Matthieu. If you need more info, let me know.
Just a small typo I corrected in the entry. I meant "the robots.txt is NOT ignored even if one sets the heritrix parameter of calculateRobotsOnly is set to false".

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
