### ISSUE TITLE
tar.gz - Documentation files in html format

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#45]
maven plugin:
 * https://github.com/walokra/markdown-page-generator-plugin
   * https://ruleoftech.com/2013/maven-plugin-to-generate-html-from-markdown
*  https://github.com/sirthias/pegdown

**Comment by mfaure** [comment]
Documentation is embedded in `/documentation` directory, and Markdown is meant to be read by humans.
I suggest this is enough to close this issue. (If someone wants to add HTML version of documentation, feel free to make a Pull Request :) )

**Comment by dzc34** [comment]
tested in [html_documentation](https://github.com/Asqatasun/Asqatasun/tree/html_documentation) branch

**Comment by dzc34** [comment]
done
