### ISSUE TITLE
INSTALLATION Firefox symlinks not created if some already exist

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#52]
## Problem description

While running the install process, symlinks are created for the firefox profile in the directory `${prefix}$TG_TMP_DIR`. If symlinks already exist and are different from the requested ones, they are not overridden, installation goes on silently, and the user is not informed.

This may lead to inconsistencies while the user thinks everything is OK (as no error was raised, nor any warning message), whereas it is not (the requested links were note created).
## expected behavior

At least rise some warning, or better: stop the install process giving the reason, even better rollback the install steps already executed.

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
