### ISSUE TITLE
"Internal server error" lors de la suppression d'audit

### ISSUE THREAD

**Issue by florianvincent** [Asqatasun/Asqatasun#53]
La tache de suppression d'audit aboutie sur une "Internal server error", dans le cas ou les audits sont lourds et ou nombreux

**Comment by dzc34** [comment]
merci @florianvincent pour ton retour.

Si je comprend bien tu as rencontré ce problème plusieurs fois ?
Peux-tu préciser "audits lourds" ? 10 000 pages, plus ? Pour quel référentiel / Niveau ?

De même "nombreux" audits, c'est combien ? 10, 50 ... 100... ?

Au niveau du message d'erreur "Internal server error"
il n'y avait pas des informations complémentaires sur l'erreur ?

**Comment by dzc34** [comment]
En supprimant plusieurs audits (plus ou moins lourd), je ne reproduis pas l'erreur. Par contre la machine est fortement sollicitée (principalement au niveau du CPU) pendant un temps très longs et le navigateur n'affiche rien pendant plusieurs minutes...

> _22 audtis de sites (6 de 10 pages, 6 de 100 pages, 6 de 1 000 pages et 4 de 10 000 pages)
> machine core i7_

**Comment by florianvincent** [comment]
Pardon pour le délai
Mais en effet, c'est arrivé lorsque j'ai supprimé de 3 gros audits (~10000)
J'imagine que ceci doit être la cause du plantage. Je ne l'ai pas eu depuis

Merci


On Sunday, January 31, 2016, Fabrice Gangler <notifications@github.com>
wrote:

> En supprimant plusieurs audits (plus ou moins lourd), je ne reproduis pas
> l'erreur. Par contre la machine est fortement sollicitée (principalement au
> niveau du CPU) pendant un temps très longs et le navigateur n'affiche rien
> pendant plusieurs minutes...
>
>
> *22 audtis de sites (6 de 10 pages, 6 de 100 pages, 6 de 1 000 pages et 4
> de 10 000 pages) machine core i7*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Asqatasun/Asqatasun/issues/53#issuecomment-177549015>.
>


-- 
*http://soundcloud.com/argh-beats/ <http://soundcloud.com/argh-beats/>*
*http://33bisrec.bandcamp.com <http://33bisrec.bandcamp.com>*

**Comment by dzc34** [comment]
pas de souci pour le délai 
et encore merci pour ton retour.

**Comment by dzc34** [comment]
@florianvincent 
j'allai oublié, si tu veux pour donner un peu de popularité sur Github à Asqatasun,
tu peux mettre une étoile et|ou forker le project. Rien d'obligatoire... ;)

**Comment by florianvincent** [comment]
avec plaisir !

2016-02-03 6:43 GMT+01:00 Fabrice Gangler <notifications@github.com>:

> @florianvincent <https://github.com/florianvincent>
> j'allai oublié, si tu veux pour donner un peu de popularité sur Github à
> Asqatasun,
> tu peux mettre une étoile et|ou forker le project. Rien d'obligatoire... ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Asqatasun/Asqatasun/issues/53#issuecomment-179025324>.
>



-- 
*http://soundcloud.com/argh-beats/ <http://soundcloud.com/argh-beats/>*
*http://33bisrec.bandcamp.com <http://33bisrec.bandcamp.com>*
