### ISSUE TITLE
How to create a new project

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#56]
How do I create a new project in asqatasun ... i just see 3 projects out of the box...??>>

**Comment by dzc34** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/6709977/12792593/e09ff026-caac-11e5-908b-ef2804463223.png)
![selection_005](https://cloud.githubusercontent.com/assets/6709977/12792599/e8a68316-caac-11e5-94b2-e429fbc84b86.png)

![selection_006](https://cloud.githubusercontent.com/assets/6709977/12792601/ecdbbcf8-caac-11e5-9323-054a8e36e81b.png)

**Comment by softwareklinic** [comment]
Thank you. Appreciate.

**Comment by mgifford** [comment]
Can this get better written into the user docs?

**Comment by dzc34** [comment]
Thank  @mgifford for your feedback. Your are right.
