### ISSUE TITLE
Shows results in French - even after clicking EN

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#57]
installed the tool on local... and ran some tests but it shows results in non EN language....

![image](https://cloud.githubusercontent.com/assets/7537289/12787883/e6d7d2ba-ca5c-11e5-9c34-7116a225af37.png)

**Comment by dzc34** [comment]
it was translated in the develop branch since 10 days.
https://github.com/Asqatasun/Asqatasun/commits/develop

Pending a new release, if you want to access a full english ihm, add a new project / Contract with Accessiweb Referential. Accessiweb is based on Wcag 2.2.

**Comment by dzc34** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/6709977/12792641/21bf48c2-caad-11e5-8d2b-9f79ba090735.png)
![selection_005](https://cloud.githubusercontent.com/assets/6709977/12792644/242e900e-caad-11e5-9588-a0942409029f.png)
![selection_006](https://cloud.githubusercontent.com/assets/6709977/12792646/256a7c30-caad-11e5-9086-86127a3cd245.png)

**Comment by softwareklinic** [comment]
Ty. Got it.

**Comment by softwareklinic** [comment]
When is the new release???

**Comment by dzc34** [comment]
As usual in libre software,
it's shipped when it's ready.

soon, we hope...
