### ISSUE TITLE
What is the difference between tanaguru and asqatasun

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#60]

**Comment by dzc34** [comment]
Today, only the information that 
you can read in the [CHANGELOG.txt
](https://github.com/Asqatasun/Asqatasun/blob/master/CHANGELOG.txt)
Soon, a little more information to read...

**Comment by mfaure** [comment]
@softwareklinic 

* Short version: Asqatasun is the fork of Tanaguru from its creators.
* Full story here: [Asqatasun history](http://asqatasun.org/#asqatasun-history)
