### ISSUE TITLE
Where can we find the Asqatasun Jenkins plugin

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#61]

**Comment by dzc34** [comment]
it's coming...

**Comment by softwareklinic** [comment]
Can I use tanaguru plugin for now…??? With Asqatasun runner?

**Comment by dzc34** [comment]
#66

**Comment by mfaure** [comment]
Here is the[Asqatasun Jenkins Plugin](https://github.com/Asqatasun/Asqatasun-jenkins-plugin). @jkowalczyk may have a few things to add but that should be OK.
