### ISSUE TITLE
In which scenarios / cases is the EMAIL sent

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#62]
When I configured the tool on my personal mac, i saw emails flying in case of failures. But, i dont see that happening from my work mac (not on a corporate network - no proxy - just over a public wifi...)

IS it possible to configure when should the tool send emails??

**Comment by mfaure** [comment]
(just see this issue has got an answer)

You can't decide when the emails can be sent or not in the application. From a system point of view, if you have an SMTP server configured, all unsent emails will be spooled in a buffer, and will be sent when you are connected again.
