### ISSUE TITLE
SEO + Rgaa2 :  export ods, csv or pdf does not work

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#63]
In a docker container, nothing in the logs ...

**Comment by softwareklinic** [comment]
I would recommend to install this on a linux server and try out - docker is kind of limited and doesn't save everything... on restart..

**Comment by dzc34** [comment]
thank you for helping me

the export (ods, csv, pdf) works fine
for RGAA audit but not for SEO audit...

**Comment by dzc34** [comment]
the export (ods, csv, pdf) 
works fine for Rgaa 3 and Accessiweb 2 audit 
but not for SEO / Rgaa 2 audit
http://forum.asqatasun.org/t/erreur-lors-de-lexport-daudit/131/8

**Comment by dzc34** [comment]
same issue: #67 PDF and Russian lang, and themplate PDF

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
