### ISSUE TITLE
Jenkins plugin

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#66]
Can i use the tanaguru plugin with asqatasun.... i don't see any asqatasun jenkins plugin available

**Comment by dzc34** [comment]
> i don't see any asqatasun jenkins plugin available

it's coming...

----
> Can i use the tanaguru plugin with asqatasun...

I 'm not sure it will work...  
ping @jkowalczyk @mfaure

**Comment by mfaure** [comment]
You could use [Asqatasun Jenkins Plugin](https://github.com/Asqatasun/Asqatasun-jenkins-plugin). @jkowalczyk may have a few things to add but that should be OK.
