### ISSUE TITLE
PDF and Russian lang, and themplate PDF

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#67]
Hello all, i try install IText 4.2.1, and on download have this error:

```
05-02-2016 17:29:56:775 91732 ERROR org.asqatasun.webapp.controller.AuditExportResultController  - net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expr$
```

```
1. Syntax error on token "Search", ; expected
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                    <---->
2. Engine cannot be resolved to a type
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                           <---->
3. Syntax error on token "">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"", delete this token
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                                              <-------------------------------------------------->
4. Syntax error on token "Search", ; expected
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                    <---->
5. Engine cannot be resolved to a type
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                           <---->
6. Syntax error on token "">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"", delete this token
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                                              <-------------------------------------------------->
7. Syntax error on token "Search", ; expected
                value = "Mark : 100%  -  Referential : <abbr title="Search Engine Optimisation">SEO</abbr> 1.0  -  Level : Ð^ÚÑ^ÀÐ¸Ñ^ÂÐ¸Ñ^ÇÐµÑ^ÁÐºÐ¸Ðµ"; //$JR_EXPR_ID=10$
                                                                    <---->

```

If i download other not translated report, all normal and i have PDF.

And second question - where i can find themplate for PDF file? I want some change final file :)

**Comment by gwynnbleiidd** [comment]
Ok i fix this with delete `""`
But have problem with encoding
http://picsee.net/upload/2016-02-08/ee02a9bc7634.png

**Comment by dzc34** [comment]
> here i can find themplate for PDF file? I want some change final file :)

no template but config files :
[/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export](https://github.com/Asqatasun/Asqatasun/tree/master/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export)

**Comment by dzc34** [comment]
> here i can find themplate for PDF file? I want some change final file :)

no template but config files :
[/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export](https://github.com/Asqatasun/Asqatasun/tree/master/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export)

**Comment by dzc34** [comment]
> But have problem with encoding

@gwynnbleiidd do you have the same problem with the csv|ods export ?

**Comment by gwynnbleiidd** [comment]
@dzc34 yes, i try export and see this http://picsee.net/upload/2016-02-09/954259f20e23.png
What i did wrong?

**Comment by mfaure** [comment]
hum... maybe an encoding/i18n issue when calling the export lib.
@jkowalczyk Am I right ?

**Comment by mfaure** [comment]
@gwynnbleiidd Thanks for your valuable feedback ! We tend to keep one Github issue per problem, so I created issue #69 for your second question

**Comment by gwynnbleiidd** [comment]
@mfaure @jkowalczyk 
I tried to replace the coding with UTF8 witout Bom.
As I transfer files from GitHub, but not local.

But the same result, corrected the files connected with the SEO test. Still some it can is necessary?

**Comment by jkowalczyk** [comment]
Hi, 

Can we have a look at your i18n files in russian (.properties)? Do you have a dedicated branch ? 
These strings are not stored in db but directly read from these files.

Regards 

Koj

**Comment by gwynnbleiidd** [comment]
@jkowalczyk hm... Try this https://github.com/gwynnbleiidd/Asqatasun/tree/translate
I'm new to git, not quite sure that the translation correctly set up branch)

**Comment by dzc34** [comment]
duplicate #63
