### ISSUE TITLE
Allow setting cookies for crawler?

### ISSUE THREAD

**Issue by benpatterson** [Asqatasun/Asqatasun#68]
Hi - I'm sorry if this is obvious, but I was unable to find it so I thought I'd ask.

For the crawler, is it possible to use or set cookies? I did not see anything apparent in the code, but I could have missed it as well.

If this is not possible today, could you make a suggestion or two on which module would be the appropriate place for implementing it? [For example, I was going to start looking in CrawlerImpl, but if that's the wrong place to start, I'd love a hint.]

Thanks for any help.

**Comment by dzc34** [comment]
> For the crawler, is it possible to use or set cookies? 

![capture du 2016-02-09 00 00 08](https://cloud.githubusercontent.com/assets/6709977/12902318/c7ecb0a6-cec0-11e5-94db-693e7f3b543d.png)

![capture du 2016-02-09 00 00 50](https://cloud.githubusercontent.com/assets/6709977/12902308/ab41df6c-cec0-11e5-8d3e-6a0021cebf98.png)

**Comment by benpatterson** [comment]
@dzc34 thanks a lot!

I'm sorry I should've been more clear. I'd like to crawl one of my sites, which is behind a login wall, and I wonder if there's a way for me to set the session cookie. Any suggestions?

**Comment by dzc34** [comment]
I see...
you can use a "Audit Scenario" 
[/docs/en/20_User_doc/userdoc-scenario-audit.md](https://github.com/Asqatasun/Asqatasun/blob/master/docs/en/20_User_doc/userdoc-scenario-audit.md)
[/docs/en/20_User_doc/userdoc-scenario-audit-advanced.md](https://github.com/Asqatasun/Asqatasun/blob/master/docs/en/20_User_doc/userdoc-scenario-audit-advanced.md)

or a solution based IP and "user-agent" 
of the crawler, to force the session cookie in your website

> If this is not possible today, could you make a suggestion or two on which module would be the appropriate place for implementing it? [For example, I was going to start looking in CrawlerImpl, but if that's the wrong place to start, I'd love a hint.]

ping @mfaure @jkowalczyk

**Comment by jkowalczyk** [comment]
Hi, 

The scenario mode deals with applicative authentication, as explained by dzc34 in the previous post.

To deal with authentication with the crawler, you need to dig into the crawler component (CrawlerImpl is a good start). The idea is to play with the heritrix set-up. I tried it out a couple of years ago, and it seems heritrix provided a dedicated bean called cookieStorage (https://github.com/Asqatasun/Asqatasun/blob/master/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/crawler/asqatasun-crawler-beans-site.xml). To use it, the "ignoreCookies" property must be set to false (that's what the "accept cookies" option is dedicated to).
You can have a look at the heritrix documentation but you must keep in mind that we use the version 3.1.1 (we cannot upgrade right now, for compatibility reasons).

Hope it helps

Koj

**Comment by dzc34** [comment]
added to #175 and closed
