### ISSUE TITLE
Where is the template file for PDF export ?

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#69]
If a user wants to modify the exported PDF, where is the template file to change ?

**Comment by dzc34** [comment]
> here i can find themplate for PDF file? I want some change final file :)

no template but config files :
[/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export](https://github.com/Asqatasun/Asqatasun/tree/master/web-app/asqatasun-web-app/src/main/webapp/WEB-INF/conf/export)
