### ISSUE TITLE
Spellchecker in SEO

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#71]
Does Asqatasun support spelling check while crawling?

**Comment by mfaure** [comment]
No it doesn't, but as long as you can create your own rules, one can imagine a "spell checking rule" (you'll have to find/implement the spell checker, ispell ?)

**Comment by softwareklinic** [comment]
Let
Me check on that



Regards,
Keyur

On Feb 15, 2016, at 12:43 PM, Matthieu FAURE <notifications@github.com<mailto:notifications@github.com>> wrote:


No it doesn't, but as long as you can create your own rules, one can imagine a "spell checking rule" (you'll have to find/implement the spell checker, ispell ?)
