### ISSUE TITLE
Installation on RHEL or other linux flavors

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#72]
Can I install asqatasun on any other linux flavors? than ubuntu....

**Comment by mfaure** [comment]
Yes you can, it's already been done.

I suggest to use the [asqatasun forum](http://forum.asqatasun.org/) for broad questions. We try to keep Github issues for bugs. Thank you for your understanding (and I, and certainly other people, would be glad to answer on the forum :) )
