### ISSUE TITLE
Cyrillic country code top-level domain

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#73]
Hello have some bug) If i add domaine like http://сервис-трезвый-водитель.рф/
System not add, about Cyrillic domaine here - https://en.wikipedia.org/wiki/.%D1%80%D1%84
Try use Punycode, like this https://www.punycoder.com/, but have error too.

**Comment by dzc34** [comment]
not only cyrillic
same result width http://www.citroën.fr
![selection_007](https://cloud.githubusercontent.com/assets/6709977/13127941/b771a83a-d5d2-11e5-8b71-7c931ad71f91.png)

**Comment by dzc34** [comment]
Closed as we've moved to gitlab https://gitlab.com/asqatasun/Asqatasun
