### ISSUE TITLE
About RGAA and Accessiweb?

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#74]
I welcome, whether there is a description of these tests?
I found in French, but their transfer is difficult for me. Perhaps found English articles about tests, we want to translate and write for ourselves :)

**Comment by mfaure** [comment]
Don't bother with Accessiweb, it's outdated ; just focus on RGAA v3 (and SEO)

RGAA 3 translation (from french to english) has been pushed. I will put it in [Asqatasun Transifex](https://www.transifex.com/asqatasun/asqatasun/) soon and warn you. This way it will be easier for you (and anybody) to translate it to Russian.

**Comment by gwynnbleiidd** [comment]
I not about the translation in system, I about the description that such RGAA 2.2 and 3.0. For example on Accessiweb saw the site http://www .accessiweb.org/, whether there is somewhere a description of RGAA?

**Comment by mfaure** [comment]
OK, you're talking about the explanation available for each test. By now those texts only exist in French :/

**Comment by gwynnbleiidd** [comment]
Ok... i find Référentiel général d’accessibilité pour les Administrations :)
Yes, about them. Until I found decryption of RGAA on French, I will try to study it.

**Comment by mfaure** [comment]
Here are some resources on RGAA 3 in french:

https://references.modernisation.gouv.fr/referentiel-technique-0
https://github.com/DISIC

**Comment by softwareklinic** [comment]
Which one covers WCAG 2.0?
