### ISSUE TITLE
xvfb start

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#78]
Hello, i try use test server. And have some problem with XVFB
I add script, after i try start have this:

```
root@gb:/# chmod +x /etc/init.d/xvfb
root@gb:/# update-rc.d xvfb defaults
update-rc.d: using dependency based boot sequencing
root@gb:/# /etc/init.d/xvfb start
/etc/init.d/xvfb: 24: /etc/init.d/xvfb: Syntax error: word unexpected (expecting "in")
```
Change #!/bin/sh to #!/bin/bash

And after i have this:
```
root@gb:/home/asqatasun-4.0.0.i386# /etc/init.d/xvfb start
/etc/init.d/xvfb: line 24: syntax error near unexpected token `start'
/etc/init.d/xvfb: line 24: `start)'
```
How fix? On board Debian.

**Comment by mfaure** [comment]
@gwynnbleiidd I transfered your question question to the forum: http://forum.asqatasun.org/t/syntax-error-with-xvfb-start/84

The usage is:

* Github: bugs, pull requests
* Forum: questions
