### ISSUE TITLE
Have a global export (scope page + scope site + global data)

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#79]
Add pdf/csv export for this page.
This good page for test full site :)

**Comment by gwynnbleiidd** [comment]
I will add is expanded a bit later that wants to be seen.
Now I try to collect all thoughts in a single whole)

**Comment by mfaure** [comment]
Hi @gwynnbleiidd you're right, there is no global export or site-wide export. That could be a contribution.

**Comment by dzc34** [comment]
@mfaure  why did you close this issue if  it could be a contribution ?

**Comment by mfaure** [comment]
@dzc34 because the issue is "solved" : feature not existent by now.

**Comment by mfaure** [comment]
@dzc34 you're right, I leave it open with the Feature Request flag

**Comment by dzc34** [comment]
added to #175 and closed
