### ISSUE TITLE
Setting arbitrary headers for all requests on a crawl

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#84]
> We would like to be able to navigate some of your internal 
> security while doing a crawl test. Ideally this would mean support:
> -  setting arbitrary headers for all requests on a crawl.

ping @e0d @benpatterson

**Comment by benpatterson** [comment]
Thanks for logging it, @dzc34 !

I won't be able to tackle this issue any time soon, unfortunately. But I'm setting myself to watch this to see if it moves. Thanks for porting it over.

**Comment by dzc34** [comment]
added to #175 and closed
