### ISSUE TITLE
multiple-containers Docker images

### ISSUE THREAD

**Issue by llaumgui** [Asqatasun/Asqatasun#87]
Hi,

For the multiple-containers Docker image, install script is in build script. If I build images on 2 different docker-engines I can have 2 different images. It is a **bad practice**.

I propose to:
1. Modify _install.sh_ to run with or without docker context.
2. Install Asqatasun without DB and configuration in build.
3. Install DB from `docker exec`
4. Allow to use environment variables in Asqatasun to pass DB parameters.

Best regards

**Comment by llaumgui** [comment]
If you do 1 and 4 I can do 2 & 3.

**Comment by jkowalczyk** [comment]
I don't get it. 
What do you mean by "can have 2 different images"? 
What about the step2? what is behind "without DB and configuration in build"?

**Comment by llaumgui** [comment]
Hi,

>  What do you mean by "can have 2 different images"? 

Make build on Docker compose doesn't allow to share image in Hub. Installation process is in my Image with all personalization arguments called by install.sh.

For me personalization must move in environment variable.

**Comment by jkowalczyk** [comment]
You're completely right.

We plan to use the flyway framework, to delegate the sql script execution to the software layer (and thus deal with the update process more easily).

This way, the db parameters can be passed as environment variables, and all is executed on startup. We can also more easily compose our docker with the service on one side, and the db on the other side. 

Does it fit your need?

**Comment by mfaure** [comment]
Hi LLaumgui ;)

I'm not sure your "environment variables" are related to FlyWay but to the Docker way to pass parameters. Do you have an example of docker image that could inspire us ?

**Comment by jkowalczyk** [comment]
The mysql docker image provides a lot of Environment Variables like MYSQL_ROOT_PASSWORD, MYSQL_USER or MYSQL_DATABASE for instance.

I guess this is something we can do, if the database is populated when starting the application and not when building the application. That's why I mentionned Flyway.

But I may have misunderstood.

**Comment by llaumgui** [comment]
Yes, MySQl is a god example.

**Comment by llaumgui** [comment]
Another exemple: https://hub.docker.com/r/zabbix/zabbix-3.0/

**Comment by emexelem** [comment]
Hi there,
I was in the process of running Tanaguru in Docker container. [Here's what I achieved so far](https://gist.github.com/emexelem/b83630aed09387bb885a5cd0c3efe0a5) (which greatly looks like the docker file in this repository), until I realized that Tanaguru install script expects interactive input (confirm installation options, bypassed this by the sed command in the docker file) and a local mysql database. I thought I could continue to alter the install.sh script or split it into different fragments run from Dockerfile, but I googled a bit and found [this image](https://hub.docker.com/r/varkal/tanaguru/), whose comments led me here... :) 

I agree with the comments above. We should have 2 separated containers for the web server and for the DB, both tied together with a compose file. 
The dockerfile for the web server would be almost done, I can merge my gist with yours and do a PR if you want. I think your dockerfile has too many RUN commands (each one creates a new layer in union fs so we should try to limit them).
The tricky point will be to split the install script to move everything related to DB out of it, and put it in a dockerfile for DB built above mysql official image.
How can I help here?

**Comment by dzc34** [comment]
hi @emexelem,

First off, thanks for taking the time to contribute!

> your dockerfile has too many RUN commands (each one creates a new layer in union fs so we should try to limit them).

Only 1 RUN command for [current Dockerfile](https://github.com/Asqatasun/Asqatasun/blob/master/docker/single-container/Dockerfile)


> How can I help here?
ping @mfaure @jkowalczyk

**Comment by mfaure** [comment]
Hi @emexelem, thanks for your message ! Here are the ongoing thougts about those devops stuff.

The `install.sh` script started as a useful tiny shell script, and by years became a quite huge script. I think shell is cool but not so sexy to deal with when it gets fat. 

On another hand, we want to improve our Docker image to be fully compliant to Dockers best practices.

On a third hand, we'd also like to have a plain installer (if Docker is not wanted). In my dreams, I'd also like to have packages (.deb / .rpm). We began to investigate in those directions, some work to do.

Discussing with different people, I came to the following idea of "devops architecture":

* Have a sexy installer built with sexy and trendy technology (i.e. not Shell but something like Chef / Puppet / Ansible).
* Leverage this script to build Docker Images, or packages (even if those wouldn't be fully compliant to Debian package policy in a first time)

I recently discovered that a co-worker of mine is a Puppet expert and could provide us with hints and support. He also gave us a few [good starting points for Puppet](http://forum.asqatasun.org/t/getting-started-with-puppet/237)

So I suggest we begin to create the basics of a Puppet installer. What do you think about it @emexelem ?

**Comment by emexelem** [comment]
Hi @mfaure @jkowalczyk
I have some experience with ansible and chef but i used them to manage servers multiple libs / apps / config files. For a single webapp, i don't know if it's worth the work, considering that docker file and compose tend to cover now some areas where configuration mgmt tools ruled. 
From what i've seen of the install script, we would just need to move all stuff related to db out of the webapp dockerfile and put it in a compose file so init sql scripts can be run in a separate temporary container. Webapp should also support having its configuration (jdbc address, etc)  defined in environment variables, if not already. 

Snaps might also be a good option : http://snapcraft.io

**Comment by mfaure** [comment]
OK. So your idea would be to extract the SQL stuff from the `install.sh` to another script, to facilitate the usage of Docker Compose. Interesting idea, that could be done easily and quite quickly, and before an optional further usage of Puppet. @emexelem would that solution answer your need ?

**Comment by jkowalczyk** [comment]
Hello, 
The extraction is a good idea. 
On the other side, I'm currently working on the integration of flyway, that should help us the create all the schema on the application first start-up.
By doing so, we'll be able to remove completely the sql part of the script, and simply link an empty mysql docker image on the compose.

**Comment by mfaure** [comment]
Great news @jkowalczyk ! I think your work is for the future major release, whereas splitting the `install.sh` could be done quite quickly in a patch-release. Am I right ?

**Comment by dzc34** [comment]
added to #175
