### ISSUE TITLE
DOC Docker - Add tip for Mac OS X and Windows users

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#88]
DOC Docker - Add tip for Mac OS X and Windows users
here : https://github.com/Asqatasun/Asqatasun/tree/master/documentation/en/10_Install_doc/Docker

> "remplacer `localhost` par l’`ip` obtenu via commande `docker-machine ip default`"
https://twitter.com/goetsu/status/710803201554051072

----
> Get the host IP address.
> 
> Any exposed ports are available on the Docker host’s IP address, 
> which you can get using the docker-machine ip command:
> 
> `$ docker-machine ip default`
> 192.168.99.100

https://docs.docker.com/machine/get-started/#run-containers-and-experiment-with-machine-commands
https://docs.docker.com/machine/reference/ip/

**Comment by mfaure** [comment]
done in 9a2ab8863e7886dbe5d6d593ceef4d35bef5215c
