### ISSUE TITLE
Docker :  invalid value "dockerhost:" for flag --add-host

### ISSUE THREAD

**Issue by MecaTrouve** [Asqatasun/Asqatasun#89]
## Observed behavior

http://doc.asqatasun.org/en/10_Install_doc/Docker/index.html
```
docker run --name asqatasun -d -p 8080:8080 --add-host dockerhost:`ifconfig docker0| awk '/inet addr/{print substr($2,6)}'` asqatasun/asqatasun:v4.0.1
```
> invalid value "dockerhost:" for flag --add-host: invalid IP address in add-host: ""

## Steps to reproduce the behavior
```
docker pull asqatasun/asqatasun  
docker run --name asqatasun -d -p 8080:8080 --add-host dockerhost:`ifconfig docker0| awk '/inet addr/{print substr($2,6)}'` asqatasun/asqatasun:v4.0.1
```

## Your configuration

* Using Docker image ?  yes
```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

```
ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:5f:46:db:ae  
          inet adr:172.17.0.1  Bcast:0.0.0.0  Masque:255.255.0.0
          adr inet6: fe80::42:5fff:fe46:dbae/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:696 erreurs:0 :0 overruns:0 frame:0
          TX packets:895 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          Octets reçus:6647329 (6.6 MB) Octets transmis:163387 (163.3 K
```

**Comment by MecaTrouve** [comment]
replace 
`ifconfig docker0| awk '/inet addr/{print substr($2,6)}'`
by 
`ifconfig docker0| awk '/inet adr/{print substr($2,6)}'`

but 
`docker0| awk '/inet addr/{print substr($2,6)}`
return 72.17.0.1
not 172.17.0.1

**Comment by mfaure** [comment]
output of `locale` ?

**Comment by MecaTrouve** [comment]
```
 locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by dzc34** [comment]
`ip addr show docker0 | awk '/inet /{print substr($2,1)}' `
> 4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
>     link/ether 02:42:f8:d8:e0:29 brd ff:ff:ff:ff:ff:ff
>     inet 172.17.0.1/16 scope global docker0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::42:f8ff:fed8:e029/64 scope link 
>        valid_lft forever preferred_lft forever

`ip addr show docker0 | awk '/inet /{print substr($2,1)}' `
> 172.17.0.1/16

**Comment by dzc34** [comment]
`docker run --name asqatasun-test -d -p 8080:8080 --add-host dockerhost:`ip addr show docker0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1'` asqatasun/asqatasun`
